#version 450
#extension GL_EXT_nonuniform_qualifier : require
#extension GL_GOOGLE_include_directive : require

// Shared constants — generated by crates/renderer/build.rs from
// src/shader_constants_data.rs. Compile with:
//   glslangValidator -V -I crates/renderer/shaders composite.frag -o composite.frag.spv
#include "include/shader_constants.glsl"

// Composite pass: combines the main render pass outputs into the final
// tone-mapped swapchain image, with sky rendering for background pixels.
//
//   For geometry pixels (depth < 1.0):
//     final = direct + indirect
//     output = aces(final * exposure)
//
//   For sky pixels (depth == 1.0, exterior only):
//     Reconstruct world-space view direction from screen UV + inv_view_proj.
//     Compute sky gradient (horizon → zenith) + cloud layer + sun disc.
//     output = aces(sky * exposure)
//
// Direct and indirect are separated so SVGF can filter only the noisy
// indirect signal without blurring crisp direct-light shadows. The
// albedo attachment lets us re-multiply after demodulation.

layout(set = 0, binding = 0) uniform sampler2D hdrTex;       // direct light
layout(set = 0, binding = 1) uniform sampler2D indirectTex;  // demodulated indirect
layout(set = 0, binding = 2) uniform sampler2D albedoTex;    // surface albedo (multiplies demodulated indirect)
layout(set = 0, binding = 3) uniform CompositeParams {
    // Reserved-and-unconsumed (#1926 / REN-D8-01): the aerial-perspective
    // fallback that read these two fields was removed once
    // VOLUMETRIC_OUTPUT_CONSUMED made it permanently dead. Kept in the
    // UBO for the future REGN-driven volumetric density tint (M55 Phase 6).
    vec4 fog_color;      // xyz = RGB, w = enabled (1.0 = yes)
    // x = near, y = far, z = XCLL cubic-fog clip distance (0 = no
    // curve), w = XCLL cubic-fog falloff exponent (0 = no curve).
    // Formula (currently unconsumed by any shader — see fog_color's
    // note above and #1927 / REN-D8-02): when z > 0 && w > 0, use
    // pow(dist / z, w) instead of the linear (dist - near) / (far -
    // near) blend. See #865 / FNV-D3-NEW-06. The removed consumer was
    // exterior-gated and mixed toward sky-haze — meaningless for the
    // FNV interiors this curve targets; a future revival needs its own
    // interior-scoped branch mixing toward fog_color instead.
    vec4 fog_params;
    vec4 depth_params;   // x = is_exterior (1.0 = sky enabled), y = exposure, z = volumetric_consumed (bool as float), w = unused
    vec4 sky_zenith;     // xyz = zenith color (linear RGB), w = sun_size (cos threshold)
    vec4 sky_horizon;    // xyz = horizon color (linear RGB), w = unused
    vec4 sky_lower;      // xyz = below-horizon ground tint (WTHR SKY_LOWER), w = unused (#541)
    vec4 sun_dir;        // xyz = sun direction (world-space, normalized), w = sun_intensity
    vec4 sun_color;      // xyz = sun disc color (linear RGB), w = CLMT FNAM sun sprite idx (floatBitsToUint; 0 = procedural disc)
    vec4 cloud_params;   // x=scroll_u, y=scroll_v, z=tile_scale (0=disabled), w=texture_idx(uintBits)
    vec4 cloud_params_1; // cloud layer 1 (WTHR CNAM) — same packing as cloud_params
    vec4 cloud_params_2; // cloud layer 2 (WTHR ANAM) — same packing (M33.1)
    vec4 cloud_params_3; // cloud layer 3 (WTHR BNAM) — same packing (M33.1)
    vec4 camera_pos;     // xyz = camera position in render-origin-RELATIVE space (matches inv_view_proj; the CPU subtracts render_origin at upload), w = unused. Fog distance origin (#428) + ray origin for screen_to_world_dir (#1490).
    mat4 inv_view_proj;  // inverse view-projection for ray reconstruction
    // Underwater post-FX: xyz = water deep-color tint (linear RGB),
    // w = camera depth below water surface (world units, >0 = under).
    // The shader's final branch mixes `combined` toward `underwater.xyz`
    // by a depth-driven extinction when `underwater.w > 0`. When `w == 0`
    // the branch is a no-op.
    vec4 underwater;
} params;
layout(set = 0, binding = 4) uniform sampler2D depthTex;     // depth buffer
layout(set = 0, binding = 5) uniform usampler2D causticTex;  // R32_UINT caustic accumulator (#321)
// M55 Phase 4: volumetric froxel volume (RGBA16F).
//   rgb = inscatter radiance (HDR linear, pre-tone-map)
//   a   = extinction coefficient (1 / m)
// Sampled per-fragment with a 32-step ray-march for the in-scatter +
// transmittance modulation applied to `combined` before ACES.
layout(set = 0, binding = 6) uniform sampler3D volumetricFroxel;
// M58: bloom output mip 0 (B10G11R11_UFLOAT, half-screen). Sampled
// at full screen resolution with bilinear hardware filtering;
// added to `combined` before ACES per Frostbite §8.
layout(set = 0, binding = 7) uniform sampler2D bloomTex;
// #1257 / Phase E of #1210 — water-side caustic accumulator (R32_UINT,
// NEAREST sampler per the existing integer-format-sampling rule
// documented at composite.rs:360). Written by water.frag's
// `imageAtomicAdd` during the main render pass (#1256), read here
// after the post-render-pass barrier (#1255). Summed alongside
// `causticTex` so both writers (caustic_splat.comp for glass +
// MultiLayerParallax, water.frag for water surfaces) contribute to
// the same composited direct-light caustic term — they share the
// CAUSTIC_FIXED_SCALE fixed-point convention.
layout(set = 0, binding = 8) uniform usampler2D waterCausticTex;

// Set 1: bindless texture array from TextureRegistry — shared with the
// main geometry pipeline. Used here to sample WTHR cloud textures by index.
layout(set = 1, binding = 0) uniform sampler2D textures[];
// CAUSTIC_FIXED_SCALE from shader_constants.glsl — generated from
// src/shader_constants_data.rs. Build-time drift catch: edit
// shader_constants_data.rs, rebuild crate, recompile this shader.

// VOLUME_FAR and BLOOM_INTENSITY now come from the `#include`d header
// (auto-generated by `build.rs` from `src/shader_constants_data.rs`).
// Rich doc-blocks for both values — tuning history, lockstep targets,
// authoring rationale — live alongside the canonical Rust consts in
// `shader_constants_data.rs`. See #1126.

layout(location = 0) in vec2 fragUV;
layout(location = 0) out vec4 outColor;

vec3 aces(vec3 x) {
    const float a = 2.51;
    const float b = 0.03;
    const float c = 2.43;
    const float d = 0.59;
    const float e = 0.14;
    return clamp((x * (a * x + b)) / (x * (c * x + d) + e), 0.0, 1.0);
}

// Reconstruct world-space view direction from screen UV and inverse VP.
vec3 screen_to_world_dir(vec2 uv) {
    // NDC: x [-1,1], y [-1,1], z = 1.0 (far plane in Vulkan reversed-Z? no,
    // we use standard depth where 1.0 = far).
    vec2 ndc = uv * 2.0 - 1.0;
    vec4 clip = vec4(ndc, 1.0, 1.0);
    vec4 world = params.inv_view_proj * clip;
    // #926 / REN-D10-NEW-06 — defensive guard against a singular
    // projection matrix producing `world.w == 0`. Real perspective
    // cameras keep w strictly positive at the far plane, so the
    // clamp is a no-op on the hot path; the floor only fires for
    // degenerate matrices (zero-FOV, behind-camera ray, etc.) and
    // keeps the result finite instead of producing NaN/inf that
    // would propagate into the sky / aerial-perspective branches.
    float w = max(abs(world.w), 1e-6);
    // #1490 / REN2-05 — the ray direction runs from the CAMERA to the far-
    // plane point, so subtract the camera position (same relative space as
    // inv_view_proj). Pre-fix this returned the direction from the
    // coordinate-space origin instead: with the camera up to ~7094 u from
    // the relative origin against the 300000 far plane, sky/sun/cloud/haze
    // directions skewed up to ~1.35° (≈75% of the sun disc's angular
    // radius) and popped at every 4096-unit origin snap.
    return normalize(world.xyz / w - params.camera_pos.xyz);
}

// Compute sky color from view direction.
vec3 compute_sky(vec3 dir) {
    vec3 zenith = params.sky_zenith.xyz;
    vec3 horizon = params.sky_horizon.xyz;
    float sun_size = params.sky_zenith.w;
    float sun_intensity = params.sun_dir.w;
    // Host promises `params.sun_dir.xyz` is already normalised
    // (per `SkyParams::sun_direction` doc — "normalized, world-space
    // Y-up"). The pre-fix `normalize(...)` per fragment was wasted
    // compute on the composite fullscreen draw. See REN-D10-NEW-07
    // (audit 2026-05-09). If the host contract ever weakens, the
    // dot-product / sun-disc maths below silently degrade — re-add
    // the normalize at that point and fix the SkyParams comment.
    vec3 sun_direction = params.sun_dir.xyz;
    vec3 sun_col = params.sun_color.xyz;

    // Elevation: 0 at horizon, 1 at zenith. Clamp negative (below horizon)
    // to a slightly darkened horizon for a ground-plane approximation.
    float elevation = dir.y;

    // Sky gradient: smooth blend from horizon to zenith.
    // Use a non-linear curve so the horizon band is wider (more natural).
    float t = clamp(elevation, 0.0, 1.0);
    t = sqrt(t); // widen horizon band
    vec3 sky = mix(horizon, zenith, t);

    // Below-horizon darkening: ground approximation (not a ground
    // plane, just a colour fade toward the WTHR-authored ground
    // tint). #541 — pre-fix this branch faked the ground colour as
    // `horizon * 0.3` and dropped the authored `SKY_LOWER` group
    // entirely. The real Sky-Lower colour ships per-TOD on every
    // exterior WTHR, so the night ground is appropriately dark and
    // the sunrise / sunset fringe inherits the warm authored tint
    // without compositor-side tweaking.
    if (elevation < 0.0) {
        float below = clamp(-elevation * 3.0, 0.0, 1.0);
        sky = mix(horizon, params.sky_lower.xyz, below);
    }

    // Cloud layer 0 (from WTHR cloud_textures[0]).
    //
    // Project the upper hemisphere onto an infinite horizontal plane
    // overhead: uv = (dir.xz / dir.y) × tile_scale. This gives perspective-
    // correct foreshortening at low elevations (clouds at the horizon look
    // stretched and tile densely, directly overhead they look large and
    // slow-moving) without needing a real dome mesh.
    //
    // cloud_params.z == 0 disables the sample so the checkerboard fallback
    // handle is never read on cells without WTHR cloud data.
    // Analytic mip LOD: as elevation → 0 the UV magnitude grows as 1/elevation,
    // so the mip should rise by log2(1/elevation). Factor 0.5 keeps the transition
    // gentler than the raw log2 slope. textureLod bypasses the driver's dFdx/dFdy
    // estimate, which would see a 100x–500x UV discontinuity across horizon-fade
    // quads and snap to mip-0 (per-texel aliasing visible in #730). SH-13.
    float cloud_lod = log2(1.0 / max(elevation, 0.05)) * 0.5;

    float tile_scale = params.cloud_params.z;
    if (tile_scale > 0.0 && elevation > 0.0) {
        uint cloud_idx = floatBitsToUint(params.cloud_params.w);
        // max() floor guards against the overhead singularity (dir.y → 0)
        // producing NaN UVs. 0.05 matches ~3° of remaining foreshortening.
        vec2 uv = dir.xz / max(elevation, 0.05) * tile_scale
                + params.cloud_params.xy;
        vec4 cloud = textureLod(textures[nonuniformEXT(cloud_idx)], uv, cloud_lod);
        // Fade clouds out at the horizon so the projection singularity
        // doesn't produce an ugly stretched band right at elevation=0.
        float horizon_fade = smoothstep(0.0, 0.12, elevation);
        sky = mix(sky, cloud.rgb, cloud.a * horizon_fade);
    }

    // Cloud layer 1 (WTHR CNAM — higher-altitude deck, opposite drift direction).
    // tile_scale_1 == 0.0 when no CNAM texture was loaded; the branch is
    // skipped entirely so the bindless array is never sampled with index 0.
    float tile_scale_1 = params.cloud_params_1.z;
    if (tile_scale_1 > 0.0 && elevation > 0.0) {
        uint cloud_idx_1 = floatBitsToUint(params.cloud_params_1.w);
        vec2 uv_1 = dir.xz / max(elevation, 0.05) * tile_scale_1
                  + params.cloud_params_1.xy;
        vec4 cloud_1 = textureLod(textures[nonuniformEXT(cloud_idx_1)], uv_1, cloud_lod);
        float horizon_fade_1 = smoothstep(0.0, 0.12, elevation);
        sky = mix(sky, cloud_1.rgb, cloud_1.a * horizon_fade_1);
    }

    // Cloud layer 2 (WTHR ANAM, M33.1) — same projection / fade as layer 1.
    float tile_scale_2 = params.cloud_params_2.z;
    if (tile_scale_2 > 0.0 && elevation > 0.0) {
        uint cloud_idx_2 = floatBitsToUint(params.cloud_params_2.w);
        vec2 uv_2 = dir.xz / max(elevation, 0.05) * tile_scale_2
                  + params.cloud_params_2.xy;
        vec4 cloud_2 = textureLod(textures[nonuniformEXT(cloud_idx_2)], uv_2, cloud_lod);
        float horizon_fade_2 = smoothstep(0.0, 0.12, elevation);
        sky = mix(sky, cloud_2.rgb, cloud_2.a * horizon_fade_2);
    }

    // Cloud layer 3 (WTHR BNAM, M33.1) — same projection / fade as layer 1.
    float tile_scale_3 = params.cloud_params_3.z;
    if (tile_scale_3 > 0.0 && elevation > 0.0) {
        uint cloud_idx_3 = floatBitsToUint(params.cloud_params_3.w);
        vec2 uv_3 = dir.xz / max(elevation, 0.05) * tile_scale_3
                  + params.cloud_params_3.xy;
        vec4 cloud_3 = textureLod(textures[nonuniformEXT(cloud_idx_3)], uv_3, cloud_lod);
        float horizon_fade_3 = smoothstep(0.0, 0.12, elevation);
        sky = mix(sky, cloud_3.rgb, cloud_3.a * horizon_fade_3);
    }

    // Sun disc: bright circular spot with a soft edge.
    // sun_size is cos(half-angle) of the disc — lower = wider.
    // Use a smooth transition band outside the core to avoid hard edges
    // from screen-space direction reconstruction precision.
    //
    // `elevation > 0.0` matches the cloud-layer gate convention above
    // and stops the disc painting over the below-horizon ground tint
    // at sunset/sunrise (the sky-lower mix at L107 produces a "ground"
    // colour that the disc would otherwise overwrite). #800.
    float cos_angle = dot(dir, sun_direction);
    float sun_edge_start = sun_size - 0.002; // soft outer fringe
    if (cos_angle > sun_edge_start && elevation > 0.0) {
        float t = (cos_angle - sun_edge_start) / (1.0 - sun_edge_start);
        t = smoothstep(0.0, 1.0, t);
        // Core is bright, edge fades smoothly.
        float core = smoothstep(sun_size, 1.0, cos_angle);
        float disc = mix(t * 0.5, 1.0, core);

        // #478 — when CLMT FNAM ships a sun sprite (non-zero index),
        // sample it within the disc and multiply by sun_col; otherwise
        // fall back to the flat sun_col (pre-fix behaviour). The UV
        // comes from projecting `dir` onto a tangent plane
        // perpendicular to `sun_direction` and scaling so the texture
        // fills the disc radius.
        uint sun_tex_idx = floatBitsToUint(params.sun_color.w);
        vec3 disc_color = sun_col;
        if (sun_tex_idx != 0u) {
            // Local 2D basis on the plane perpendicular to sun_direction.
            vec3 up_world = abs(sun_direction.y) < 0.99
                ? vec3(0.0, 1.0, 0.0)
                : vec3(0.0, 0.0, 1.0);
            vec3 tangent = normalize(cross(up_world, sun_direction));
            vec3 bitangent = cross(sun_direction, tangent);

            // Disc radius in tangent-plane units: `sqrt(1 - sun_size^2)`
            // matches the angular half-width on the unit sphere. We
            // normalise by this so the sprite fills the disc exactly.
            float disc_r = sqrt(max(0.0, 1.0 - sun_size * sun_size));
            vec2 uv = vec2(dot(dir, tangent), dot(dir, bitangent)) / max(disc_r, 1e-4);
            uv = uv * 0.5 + 0.5;
            // Force mip 0. Default `texture()` uses derivative-based
            // mip selection which goes badly wrong here: the UV is
            // divided by `disc_r` (~0.017 for a ~1° wide sun) so
            // adjacent-pixel UV deltas are ~0.06 even though both
            // pixels sit inside a 100-pixel-wide disc. The sampler
            // then picks mip 4-5 of a 256×256 sprite and the sun
            // renders as ~8 visible texels (~16 pixels each — see
            // the user-reported screenshot, ByroRedux | 1 FPS frame
            // 2026-05-24). The sprite is supposed to look sharp
            // regardless of disc screen-size; mip 0 + bilinear gives
            // ~2.5 source texels per output pixel at typical disc
            // widths, which is supersampling (sharp, no aliasing).
            // Sub-pixel discs at very large render distances would
            // alias on mip 0, but the disc is bright enough that
            // small-disc aliasing is invisible against `sun_intensity`.
            vec4 sprite = textureLod(textures[nonuniformEXT(sun_tex_idx)], uv, 0.0);
            disc_color = sun_col * sprite.rgb;
        }

        sky += disc_color * sun_intensity * disc;
    }

    // Sun glow: soft radial halo around the sun.
    //
    // #799 — multiply by `sun_intensity` so the halo fades with the
    // disc through the day/night ramp. Pre-fix the disc faded
    // correctly (line 222) but the halo stayed at constant 0.15 *
    // sun_col, so a WTHR with non-zero `SKY_SUN[NIGHT]` (e.g.
    // Skyrim's MoonShadow) painted a faint warm halo at midnight.
    //
    // Falloff tightened to `pow(., 8)` × 0.10 (was `pow(., 4)` × 0.15)
    // on the Markarth 2026-05-10 probe. The wider 4-power halo at
    // `sun_intensity = 4` was adding +0.28 RGB to the sky ~33° off the
    // sun direction; ACES tonemap then pushed the entire visible
    // upper hemisphere to pale-white in any view including the sun's
    // half of the sky. The `pow(., 8)` curve concentrates the halo
    // to ~15° around the disc — preserves the bright sun region
    // without washing the rest of the sky.
    float glow = max(cos_angle, 0.0);
    glow = pow(glow, 8.0);
    sky += sun_col * glow * 0.10 * sun_intensity;

    return sky;
}

void main() {
    vec4 direct4 = texture(hdrTex, fragUV);
    vec3 direct = direct4.rgb;

    float depth = texture(depthTex, fragUV).r;
    bool is_sky = (depth >= 0.9999) && (params.depth_params.x > 0.5);

    if (is_sky) {
        // Sky pixel: reconstruct view direction and compute sky color.
        vec3 dir = screen_to_world_dir(fragUV);
        vec3 sky = compute_sky(dir);

        float exposure = params.depth_params.y;  // host-set; default 0.85 (DEN-10)
        // Pass `direct4.a` through (mirroring the geometry branch at
        // line 279) so the alpha-blend marker bit `DEN-6 / #676`
        // preserves through TAA stays consistent across both sky and
        // geometry pixels. Sky pixels by construction don't have a
        // glass surface in front of them today, so today's
        // `direct4.a` on a sky-branch fragment is zero — but a future
        // decal pass / transparent UI / lens-flare feature that asks
        // "is this swapchain pixel sky?" via swapchain alpha would
        // see an asymmetric "1.0 = sky, anything else = geometry"
        // contract that's harder to reason about than the symmetric
        // "alpha is the marker bit, branch on it the same way."
        // DEN-11.
        vec3 sky_tonemapped = aces(sky * exposure);
        // Underwater post-FX on the sky branch — the camera looking
        // up through the water surface should also see the deep tint
        // when submerged. Same model as the geometry branch (see the
        // matching block at the end of the geometry path).
        if (params.underwater.w > 0.0) {
            float extinction = clamp(1.0 - exp(-params.underwater.w / 120.0), 0.0, 0.85);
            vec3 underwater_tonemap = aces(params.underwater.xyz * exposure);
            sky_tonemapped = mix(sky_tonemapped, underwater_tonemap, extinction);
        }
        outColor = vec4(sky_tonemapped, direct4.a);
    } else {
        // Geometry pixel: combine direct + (indirect × albedo) and tone map.
        // The shader wrote lighting-only indirect (no local albedo) so
        // SVGF operates on a texture-free signal; multiply here to
        // re-apply surface color. See #268.
        vec3 indirect = texture(indirectTex, fragUV).rgb;
        vec3 albedo = texture(albedoTex, fragUV).rgb;

        // Caustic (#321): refracted-light scatter from the caustic_splat
        // pass. Stored as fixed-point luminance in a R32_UINT accumulator;
        // decode here and add a warm-white contribution scaled by the
        // receiver's own albedo so colored surfaces pick up the caustic
        // with their own tint.
        //
        // #1257 / Phase E of #1210 — sum the water-side caustic
        // accumulator alongside the glass-/MultiLayerParallax-side
        // one. Both writers share `CAUSTIC_FIXED_SCALE` (the
        // generated `#define` in `shader_constants.glsl`) so their
        // fixed-point sums are on a unified luminance basis; one
        // `causticLum` carries the combined contribution downstream.
        uint causticRaw = texelFetch(causticTex, ivec2(gl_FragCoord.xy), 0).r;
        uint waterCausticRaw = texelFetch(waterCausticTex, ivec2(gl_FragCoord.xy), 0).r;
        // #1575 — promote each accumulator to float BEFORE the add so the sum
        // can't wrap u32. Each raw can independently climb toward the
        // 0xFFFFFFFF per-deposit ceiling (caustic_splat.comp clamps each
        // deposit, not the running sum of the two textures); adding two large
        // uints wraps mod 2^32 to ~0 → a black pixel the post-divide firefly
        // cap cannot recover.
        float causticLum = (float(causticRaw) + float(waterCausticRaw)) / CAUSTIC_FIXED_SCALE;
        // Firefly cap on the COMBINED caustic luminance (TARGET 2). The focal
        // cusp under glass spheres / water sums thousands of forward-splat
        // deposits (imageAtomicAdd) into a few pixels; under camera motion the
        // caustic accumulator is cleared per-frame (no EMA smoothing), so the
        // un-averaged cusp peak flickers as bright splotches. Bound the peak
        // before it enters `combined`. Indirect-only: `direct` is added
        // separately below, so the light source is untouched. Pre-ACES linear
        // ceiling — start conservative and tune down per the TARGET 2 bench.
        const float CAUSTIC_FIREFLY_MAX = 16.0;
        causticLum = min(causticLum, CAUSTIC_FIREFLY_MAX);
        vec3 caustic = albedo * causticLum;

        vec3 combined = direct + indirect * albedo + caustic;

        // M55 Phase 3 — volumetric modulation via single sampler3D tap.
        // The volumetric pipeline pre-integrates `(∫inscatter, T_cum)`
        // along the view ray per froxel column in a compute pass; here
        // we just look up the value at the fragment's depth slice and
        // modulate `combined`. Done in HDR-linear (pre-ACES) per
        // Frostbite §5.3 so the tone-mapper sees the inscattered
        // radiance and the scene together.
        //
        // The volumetric volume is screen-space in xy and depth-slice
        // in z under linear distribution, so the sample coordinate is
        // (fragUV, worldDist / VOLUME_FAR). No NDC projection needed,
        // no per-step loop.
        if (depth < 0.9999) {
            vec2 ndc_xy = fragUV * 2.0 - 1.0;
            vec4 clip = vec4(ndc_xy, depth, 1.0);
            vec4 world = params.inv_view_proj * clip;
            vec3 worldPos = world.xyz / world.w;
            float worldDist = length(worldPos - params.camera_pos.xyz);
            // clamp(0, 1 - eps): max-slice texel still samples within
            // the volume rather than the CLAMP_TO_EDGE neighbour, which
            // would over-extrapolate transmittance for fragments past
            // the volume far plane.
            //
            // #1462 (resolved) — this texel-EDGE mapping now agrees
            // with `integrate`'s front-of-slab Riemann storage and
            // `inject`'s front-edge sampling (see the reconciliation
            // note in `volumetrics_inject.comp`). All three passes
            // share one convention.
            float slice = clamp(worldDist / VOLUME_FAR, 0.0, 0.9999);
            vec4 vol = texture(volumetricFroxel, vec3(fragUV, slice));
            // vol.rgb = ∫inscatter accumulated 0..slice (HDR-linear)
            // vol.a   = cumulative transmittance through 0..slice
            //
            // M55 Phase 2c volumetric contribution was gated off
            // 2026-05-09 (per-froxel single-shadow-ray produced
            // ~8px-wide vertical banding on Prospector Saloon lantern
            // content) and re-enabled once M-LIGHT v2 (the 3x3 spatial
            // blur in `volumetrics_integrate.comp`) resolved it — see
            // `volumetrics::VOLUMETRIC_OUTPUT_CONSUMED`.
            //
            // `params.depth_params.z` mirrors that host-side const, so
            // it's always 1.0 here; `vol.a` genuinely carries cumulative
            // transmittance and `vol.rgb` in-scattered radiance. Frostbite
            // §5.3 standard form: attenuate FIRST (energy lost to
            // absorption between camera and fragment), then ADD inscatter
            // (radiance that arrived via in-scattering, NOT itself
            // attenuated by `T_cum` — the integrate pass already weighted
            // each slab's contribution by its own running transmittance).
            combined = combined * vol.a + vol.rgb;
        }

        // M58 — bloom add. Sampled with bilinear from mip 0 of the
        // bloom up-pyramid (half-screen resolution; hardware filter
        // upscales to full screen for free). Added in HDR-linear
        // (pre-ACES) so the tone-mapper compresses scene + bloom
        // together — bright surfaces' glow doesn't clip independently
        // of the surface. `fragUV` in [0,1]² works directly against
        // the half-res bloom view.
        vec3 bloom = texture(bloomTex, fragUV).rgb;
        combined += bloom * BLOOM_INTENSITY;

        float exposure = params.depth_params.y;  // host-set; default 0.85 (DEN-10)

        // Tone-map the unfogged combined HDR to display space FIRST,
        // then apply fog as a display-space mix. Pre-#784 the fog
        // was mixed into HDR-linear `combined` and then both went
        // through ACES together — XCLL-authored `fog_color` values
        // (raw monitor-space floats per `feedback_color_space.md`,
        // typically 0.05-0.4 on interior cells) blended in linear
        // HDR appear perceptually amplified once the result is
        // tone-mapped, producing a visible yellow / sepia distance
        // wash on distant interior surfaces. Display-space mix
        // matches the perceptual intent of the authored fog values
        // and preserves #428's SVGF-coherence goal (fog applied at
        // composite, not in the geometry pass) since SVGF reads
        // un-fogged HDR upstream regardless of where the mix lands
        // on the post-tone-map side.
        vec3 tonemapped = aces(combined * exposure);

        // Aerial-perspective fog fallback (Markarth probe 2026-05-10)
        // stood in for the volumetric froxel pipeline while M-LIGHT v2
        // was gated off. `VOLUMETRIC_OUTPUT_CONSUMED` (volumetrics.rs)
        // flipped to `true` once M-LIGHT v2 landed — `depth_params.z` is
        // now permanently pinned to 1.0 (draw.rs), so this fallback's
        // `depth_params.z < 0.5` guard can never pass. Removed per the
        // lockstep note this branch used to carry (#1926 / REN-D8-01);
        // the volumetric path (`vol.a` / `vol.rgb` above) is the sole
        // exterior fog source now. `fog_color` / `fog_params` stay in
        // the UBO, reserved-and-unconsumed for the future REGN-driven
        // volumetric density tint (M55 Phase 6) — nothing in this
        // shader reads them today.

        // ── Underwater post-FX ────────────────────────────────────────
        //
        // Drives a depth-based tint toward the active water material's
        // `deep_color` when the camera is submerged. The CPU sets
        // `params.underwater.xyz` to the deep-color tint and
        // `params.underwater.w` to the camera's depth below the
        // surface; `w == 0` keeps the branch a no-op.
        //
        // Extinction model: Beer-Lambert with a 1/120-wu falloff,
        // chosen so a 60-wu submersion (head just under) sits at
        // ~40% tint and a 240-wu submersion saturates at ~85% tint.
        // The cap at 0.85 prevents full black when the player dives
        // arbitrarily deep — the scene stays legible.
        if (params.underwater.w > 0.0) {
            float extinction = 1.0 - exp(-params.underwater.w / 120.0);
            extinction = clamp(extinction, 0.0, 0.85);
            // Tone-map the underwater colour with the same exposure
            // so the mix doesn't drag the scene into HDR space where
            // ACES would re-bend it. The underwater colour is
            // already authored in display-linear (per the
            // `feedback_color_space.md` policy on Gamebryo colour
            // bytes), so an ACES pass on a tone-mapped target is
            // visually correct here.
            vec3 underwater_tonemap = aces(params.underwater.xyz * exposure);
            tonemapped = mix(tonemapped, underwater_tonemap, extinction);
        }

        outColor = vec4(tonemapped, direct4.a);
    }
}
