#version 450
#extension GL_EXT_nonuniform_qualifier : require
#extension GL_GOOGLE_include_directive : require

// Shared constants — generated by crates/renderer/build.rs from
// src/shader_constants_data.rs. Compile with:
//   glslangValidator -V -I crates/renderer/shaders composite.frag -o composite.frag.spv
#include "include/shader_constants.glsl"
// #3742 — BLUE_NOISE_RANKS, shared verbatim with volumetrics_inject.comp.
#include "include/blue_noise.glsl"

// Scene-composition pass: combines the main render-pass outputs into one
// render-resolution linear-HDR image, with sky rendering for background
// pixels. Upscaling and display mapping happen in later frame-graph passes.
//
//   For geometry pixels (depth < 1.0):
//     final = direct + indirect
//     output = final
//
//   For sky pixels (depth == 1.0, exterior only):
//     Reconstruct world-space view direction from screen UV + inv_view_proj.
//     Compute sky gradient (horizon → zenith) + cloud layer + sun disc.
//     output = sky
//
// Direct and indirect are separated so SVGF can filter only the noisy
// indirect signal without blurring crisp direct-light shadows. The
// albedo attachment lets us re-multiply after demodulation.

layout(set = 0, binding = 0) uniform sampler2D hdrTex;       // direct light
layout(set = 0, binding = 1) uniform sampler2D indirectTex;  // demodulated indirect
layout(set = 0, binding = 2) uniform sampler2D albedoTex;    // surface albedo (multiplies demodulated indirect)
layout(set = 0, binding = 3) uniform CompositeParams {
    vec4 fog_color;      // xyz = beyond-grid aerial tint, w = enabled
    // x = near, y = far, z = XCLL cubic-fog clip distance (0 = no
    // curve), w = XCLL cubic-fog falloff exponent (0 = no curve).
    // Runtime no longer evaluates this non-physical curve. It remains in the
    // contract until XCLL/WTHR values are fitted offline into sigma_t tables.
    vec4 fog_params;
    vec4 depth_params;   // x = is_exterior, y = uintBitsToFloat(debug flags),
                         // z = uintBitsToFloat(structured debug mode),
                         // w = frame index
    vec4 volume_params;  // x = grid far, y = linear floor, z = linear fraction, w = dither amplitude
    vec4 height_fog_params; // x = sigma_t0, y = scale height, z = albedo, w = fallback enabled
    vec4 sky_zenith;     // xyz = zenith color (linear RGB), w = sun_size (cos threshold)
    vec4 sky_horizon;    // xyz = horizon color (linear RGB), w = froxel grid
                         // slice count (#2470 — texel-center correction for
                         // the volumetricFroxel sampler3D tap below)
    vec4 sky_lower;      // xyz = below-horizon ground tint (WTHR SKY_LOWER), w = unused (#541)
    vec4 sun_dir;        // xyz = sun direction (world-space, normalized), w = sun_intensity
    vec4 sun_color;      // xyz = sun disc color (linear RGB), w = CLMT FNAM sun sprite idx (floatBitsToUint; 0 = procedural disc)
    vec4 cloud_params;   // x=scroll_u, y=scroll_v, z=tile_scale (0=disabled), w=texture_idx(uintBits)
    vec4 cloud_params_1; // cloud layer 1 (WTHR CNAM) — same packing as cloud_params
    vec4 cloud_params_2; // cloud layer 2 (WTHR ANAM) — same packing (M33.1)
    vec4 cloud_params_3; // cloud layer 3 (WTHR BNAM) — same packing (M33.1)
    vec4 weather_params; // rain, snow, thunder frequency, session seconds
    vec4 weather_wind; // wind direction x/z, normalized speed, reserved
    vec4 weather_lightning; // lightning RGB, moon glare
    vec4 weather_sky; // stars RGB, sun glare
    vec4 weather_aurora; // aurora intensity, follows-sun flag, procedural cloud coverage, reserved
    vec4 cloud_tint_0; // PNAM/JNAM tint + alpha
    vec4 cloud_tint_1;
    vec4 cloud_tint_2;
    vec4 cloud_tint_3;
    vec4 camera_pos;     // xyz = camera position in render-origin-RELATIVE space (matches inv_view_proj; the CPU subtracts render_origin at upload). Fog distance origin (#428) + ray origin for screen_to_world_dir (#1490). w = height-fog reference altitude (REN-D16-01 / #2225), same relative space as xyz — ground height near the camera, or camera Y as a fallback.
    mat4 inv_view_proj;  // inverse view-projection for ray reconstruction
    // xyz = water deep-color tint (linear RGB), w = authored Beer-Lambert
    // extinction (0..1). Presentation still owns the final underwater grade;
    // composite uses this field for the bounded sun-aligned shaft term below.
    vec4 underwater;
    // x = water-side caustic accumulator (binding 8, waterCausticTex) is
    // genuinely live this frame (1.0) vs. absent and fallback-bound to
    // the glass/MultiLayerParallax accumulator's own view (0.0) — the
    // real water_caustic_accum failed to allocate at init or a resize
    // (VRAM pressure). In the fallback case binding 8 aliases binding 5
    // (causticTex), so summing both would double-count the glass
    // contribution instead of contributing zero. yzw reserved. #2508.
    vec4 caustic_flags;
} params;
layout(set = 0, binding = 4) uniform sampler2D depthTex;     // depth buffer
layout(set = 0, binding = 5) uniform usampler2DArray causticTex; // RGB in three R32_UINT layers (#321)
// M55 Phase 4: volumetric froxel volume (RGBA16F).
//   rgb = inscatter radiance (HDR linear, pre-tone-map)
//   a   = extinction coefficient (1 / m)
// Sampled per-fragment with a 32-step ray-march for the in-scatter +
// transmittance modulation applied to `combined` before ACES.
layout(set = 0, binding = 6) uniform sampler3D volumetricFroxel;
// M58: bloom output mip 0 (B10G11R11_UFLOAT, half-screen). Sampled
// at full screen resolution with bilinear hardware filtering;
// added to `combined` before ACES per Frostbite §8.
layout(set = 0, binding = 7) uniform sampler2D bloomTex;
// #1257 / Phase E of #1210 — water-side caustic accumulator (R32_UINT,
// NEAREST sampler per the existing integer-format-sampling rule
// carried by `composite.rs`'s `nearest_sampler` field and its
// `create_sampler` call). Written by water.frag's
// `imageAtomicAdd` during the main render pass (#1256), read here
// after the post-render-pass barrier (#1255). Summed alongside
// `causticTex` so both writers (caustic_splat.comp for glass +
// MultiLayerParallax, water.frag for water surfaces) contribute to
// the same composited direct-light caustic term — they share the
// CAUSTIC_FIXED_SCALE fixed-point convention.
layout(set = 0, binding = 8) uniform usampler2D waterCausticTex;

// Set 1: bindless texture array from TextureRegistry — shared with the
// main geometry pipeline. Used here to sample WTHR cloud textures by index.
layout(set = 1, binding = 0) uniform sampler2D textures[];
// CAUSTIC_FIXED_SCALE from shader_constants.glsl — generated from
// src/shader_constants_data.rs. Build-time drift catch: edit
// shader_constants_data.rs, rebuild crate, recompile this shader.

// VOLUME_FAR and BLOOM_INTENSITY now come from the `#include`d header
// (auto-generated by `build.rs` from `src/shader_constants_data.rs`).
// Rich doc-blocks for both values — tuning history, lockstep targets,
// authoring rationale — live alongside the canonical Rust consts in
// `shader_constants_data.rs`. See #1126.

layout(location = 0) in vec2 fragUV;
layout(location = 0) out vec4 outColor;
layout(location = 1) out float outReactive;
layout(location = 2) out float outTransparency;

float hybridSliceCoordinate(float distanceAlongRay) {
    float farDistance = max(params.volume_params.x, 1.0);
    float linearDepth = clamp(params.volume_params.y, 1.0, farDistance);
    float linearFraction = clamp(params.volume_params.z, 1.0e-4, 0.9999);
    float d = clamp(distanceAlongRay, 0.0, farDistance);
    if (d <= linearDepth) {
        return linearFraction * (d / linearDepth);
    }
    return linearFraction + (1.0 - linearFraction)
        * log(d / linearDepth) / log(farDistance / linearDepth);
}

float linearViewDepth(float deviceDepth) {
    float nearPlane = max(params.fog_params.x, 1.0e-4);
    float farPlane = max(params.fog_params.y, nearPlane + 1.0);
    return nearPlane * farPlane
        / max(farPlane - deviceDepth * (farPlane - nearPlane), 1.0e-4);
}

// Depth-aware bilateral reconstruction of the coarse froxel image. Ordinary
// trilinear sampling is unsafe here: neighboring camera rays may lie on
// opposite sides of a doorway or wall and carry unrelated visibility. The
// old nearest-column resolve avoided that leak, but exposed every 4-8 pixel
// froxel as a square in compact fire, smoke, and explosion volumes. Rebuild
// the bilinear footprint explicitly and reject columns whose representative
// scene depth is incompatible with this fragment. Z remains a linear blend
// between cumulative slab back faces.
float froxelColumnDepthWeight(
    ivec2 column,
    ivec3 froxelSize,
    float referenceDepth
) {
    ivec2 depthSize = textureSize(depthTex, 0);
    ivec2 representativePixel = clamp(
        ivec2((vec2(column) + 0.5) * vec2(depthSize) / vec2(froxelSize.xy)),
        ivec2(0),
        depthSize - ivec2(1)
    );
    float candidateDepth = texelFetch(depthTex, representativePixel, 0).r;
    bool referenceIsSurface = referenceDepth < 1.0;
    bool candidateIsSurface = candidateDepth < 1.0;
    if (referenceIsSurface != candidateIsSurface) {
        return 0.0;
    }
    if (!referenceIsSurface) {
        return 1.0;
    }

    float referenceDistance = linearViewDepth(referenceDepth);
    float candidateDistance = linearViewDepth(candidateDepth);
    float tolerance = max(2.0, referenceDistance * 0.01);
    return 1.0 - smoothstep(tolerance, tolerance * 4.0,
        abs(candidateDistance - referenceDistance));
}

vec4 sampleVolumetricColumn(
    vec2 uv,
    float normalizedDepth,
    float referenceDepth
) {
    ivec3 size = textureSize(volumetricFroxel, 0);
    vec2 texelPosition = uv * vec2(size.xy) - 0.5;
    ivec2 baseColumn = ivec2(floor(texelPosition));
    vec2 blend = fract(texelPosition);

    // Convert normalized sampler coordinates to texel space. Integration
    // stores cumulative state at slab back faces; the caller remaps those
    // faces to texel centers before reaching this helper.
    float z = clamp(
        normalizedDepth * float(size.z) - 0.5,
        0.0,
        float(size.z - 1)
    );
    int z0 = int(floor(z));
    int z1 = min(z0 + 1, size.z - 1);
    float zBlend = fract(z);

    vec4 accumulated = vec4(0.0);
    float accumulatedWeight = 0.0;
    for (int y = 0; y < 2; ++y) {
        for (int x = 0; x < 2; ++x) {
            ivec2 column = clamp(
                baseColumn + ivec2(x, y),
                ivec2(0),
                size.xy - ivec2(1)
            );
            vec2 axisWeight = mix(vec2(1.0) - blend, blend, vec2(x, y));
            float weight = axisWeight.x * axisWeight.y
                * froxelColumnDepthWeight(column, size, referenceDepth);
            vec4 columnValue = mix(
                texelFetch(volumetricFroxel, ivec3(column, z0), 0),
                texelFetch(volumetricFroxel, ivec3(column, z1), 0),
                zBlend
            );
            accumulated += columnValue * weight;
            accumulatedWeight += weight;
        }
    }

    if (accumulatedWeight > 1.0e-5) {
        return accumulated / accumulatedWeight;
    }

    ivec2 nearestColumn = clamp(
        ivec2(uv * vec2(size.xy)),
        ivec2(0),
        size.xy - ivec2(1)
    );
    return mix(
        texelFetch(volumetricFroxel, ivec3(nearestColumn, z0), 0),
        texelFetch(volumetricFroxel, ivec3(nearestColumn, z1), 0),
        zBlend
    );
}

// Analytic optical depth for sigma_t(y)=sigma0*exp(-(y-y0)/H).
// Keep the horizontal-ray branch explicit: the general quotient becomes 0/0
// as dy/ds approaches zero and was a plausible source of exterior white-outs.
float heightFogOpticalDepth(
    float sigma0,
    float rayOriginY,
    float rayDirectionY,
    float distance,
    float baseHeight,
    float scaleHeight
) {
    if (sigma0 <= 0.0 || distance <= 0.0) {
        return 0.0;
    }
    float safeScale = max(scaleHeight, 1.0e-4);
    float logSigmaAtOrigin = log(sigma0)
        - (rayOriginY - baseHeight) / safeScale;
    float sigmaAtOrigin = exp(clamp(logSigmaAtOrigin, -80.0, 80.0));
    float lengthAlongRay = max(distance, 0.0);
    float slope = rayDirectionY / safeScale;
    if (abs(slope) < 1.0e-6) {
        return sigmaAtOrigin * lengthAlongRay;
    }
    if (slope > 0.0) {
        float integral = (1.0 - exp(-slope * lengthAlongRay)) / slope;
        return max(sigmaAtOrigin * integral, 0.0);
    }
    float endY = rayOriginY + rayDirectionY * lengthAlongRay;
    float logSigmaAtEnd = log(sigma0) - (endY - baseHeight) / safeScale;
    float sigmaAtEnd = exp(clamp(logSigmaAtEnd, -80.0, 80.0));
    return max((sigmaAtEnd - sigmaAtOrigin) / -slope, 0.0);
}

float preResolveDither() {
    uint frame = uint(params.depth_params.w);
    ivec2 pixel = ivec2(gl_FragCoord.xy) + ivec2(frame * 5u, frame * 3u);
    int index = (pixel.y & 7) * 8 + (pixel.x & 7);
    float rank = (float(BLUE_NOISE_RANKS[index]) + 0.5) / 64.0;
    return (rank - 0.5) * params.volume_params.w;
}

// Reconstruct world-space view direction from screen UV and inverse VP.
vec3 screen_to_world_dir(vec2 uv) {
    // NDC: x [-1,1], y [-1,1], z = 1.0 (far plane in Vulkan reversed-Z? no,
    // we use standard depth where 1.0 = far).
    vec2 ndc = uv * 2.0 - 1.0;
    vec4 clip = vec4(ndc, 1.0, 1.0);
    vec4 world = params.inv_view_proj * clip;
    // #926 / REN-D10-NEW-06 — defensive guard against a singular
    // projection matrix producing `world.w == 0`. Real perspective
    // cameras keep w strictly positive at the far plane, so the
    // clamp is a no-op on the hot path; the floor only fires for
    // degenerate matrices (zero-FOV, behind-camera ray, etc.) and
    // keeps the result finite instead of producing NaN/inf that
    // would propagate into the sky / aerial-perspective branches.
    float w = max(abs(world.w), 1e-6);
    // #1490 / REN2-05 — the ray direction runs from the CAMERA to the far-
    // plane point, so subtract the camera position (same relative space as
    // inv_view_proj). Pre-fix this returned the direction from the
    // coordinate-space origin instead: with the camera up to ~7094 u from
    // the relative origin against the 300000 far plane, sky/sun/cloud/haze
    // directions skewed up to ~1.35° (≈75% of the sun disc's angular
    // radius) and popped at every 4096-unit origin snap.
    return normalize(world.xyz / w - params.camera_pos.xyz);
}

float weather_hash21(vec2 p) {
    p = fract(p * vec2(123.34, 456.21));
    p += dot(p, p + 45.32);
    return fract(p.x * p.y);
}

// Smooth value noise for the broad cloud body. Authored WTHR cloud DDS
// layers are composited later as game-specific detail; this field prevents
// gaps between those finite sprites from exposing an implausibly empty sky.
float weather_cloud_noise(vec2 p) {
    vec2 cell = floor(p);
    vec2 local = fract(p);
    vec2 smooth_local = local * local * (3.0 - 2.0 * local);
    float a = weather_hash21(cell);
    float b = weather_hash21(cell + vec2(1.0, 0.0));
    float c = weather_hash21(cell + vec2(0.0, 1.0));
    float d = weather_hash21(cell + vec2(1.0, 1.0));
    return mix(mix(a, b, smooth_local.x), mix(c, d, smooth_local.x), smooth_local.y);
}

float weather_cloud_fbm(vec2 p) {
    // Explicit octaves let glslang fully unroll this hot sky-only path.
    float value = weather_cloud_noise(p) * 0.5333333;
    p = p * 2.03 + vec2(17.13, 9.71);
    value += weather_cloud_noise(p) * 0.2666667;
    p = p * 2.01 + vec2(8.37, 19.19);
    value += weather_cloud_noise(p) * 0.1333333;
    p = p * 2.04 + vec2(13.91, 3.17);
    value += weather_cloud_noise(p) * 0.0666667;
    return value;
}

// Continuous procedural cloud body. The return value is premultiplication-
// ready RGB + opacity. WTHR classification supplies broad coverage, its wind
// advects the field, and its PNAM/JNAM tables tint the result. Using the same
// infinite overhead plane as the authored layers keeps both representations
// locked together during camera motion and weather transitions.
vec4 weather_procedural_cloud(vec3 sky, vec3 dir, float elevation, vec3 sun_direction) {
    float coverage = clamp(params.weather_aurora.z, 0.0, 1.0);
    float horizon_fade = smoothstep(0.015, 0.16, elevation);
    vec2 wind = params.weather_wind.xz;
    float wind_speed = params.weather_wind.y;
    float time = params.weather_params.w;
    vec2 plane = dir.xz / max(elevation, 0.065);
    vec2 drift = wind * time * (0.0012 + wind_speed * 0.0065);

    // Frequencies are chosen in view-plane units rather than texture UVs:
    // the lowest octave must still cross several cells in a near-zenith
    // view, where `dir.xz / dir.y` spans only a small interval.
    vec2 broad_coord = plane * 4.75 + drift;
    float warp = weather_cloud_fbm(plane * 2.10 + drift * 0.37 + vec2(7.1, 19.3));
    broad_coord += vec2(warp - 0.5, 0.5 - warp) * 0.72;
    float broad = weather_cloud_fbm(broad_coord);
    float detail = weather_cloud_fbm(plane * 16.0 - drift * 0.61 + vec2(31.7, 11.3));
    float field = broad * 0.80 + detail * 0.20;
    float threshold = mix(0.62, 0.34, coverage);
    float density = smoothstep(threshold, threshold + 0.10, field);

    vec4 tint = (params.cloud_tint_0 + params.cloud_tint_1
        + params.cloud_tint_2 + params.cloud_tint_3) * 0.25;
    float day = smoothstep(-0.08, 0.22, sun_direction.y);
    float sun_facing = max(dot(dir, sun_direction), 0.0);
    float edge = smoothstep(0.08, 0.72, 1.0 - density)
        * pow(sun_facing, 10.0) * day;
    // One offset density tap approximates optical depth toward the sun. It
    // gives the body a darker underside and bright windward crown without a
    // full ray march, which is important because this runs for every clear-
    // depth pixel in the composition pass.
    float light_field = weather_cloud_fbm(
        broad_coord + sun_direction.xz * mix(0.18, 0.52, day)
    );
    float self_shadow = clamp((field - light_field) * 2.4 + 0.42, 0.0, 1.0);
    vec3 daylight_cloud = mix(
        vec3(0.43, 0.48, 0.56),
        vec3(0.98, 0.96, 0.91),
        1.0 - self_shadow
    );
    vec3 cloud_lit = mix(sky * 0.34, daylight_cloud, day);
    // WTHR remains the artistic colour authority, but treating its RGB as a
    // pure multiplier can collapse a bright cloud into the sky on records
    // with subdued tints (notably FNV's clear weather). Preserve enough
    // neutral daylight contrast for the body to read, then bias it toward
    // the authored tint.
    cloud_lit *= mix(vec3(1.0), max(tint.rgb, vec3(0.08)), 0.45);
    cloud_lit += params.sun_color.rgb * edge * params.sun_dir.w * 0.055;

    float authored_alpha = clamp(tint.a, 0.0, 1.0);
    float opacity = density * horizon_fade
        * mix(0.58, 0.95, coverage) * mix(0.78, 1.0, authored_alpha);
    return vec4(cloud_lit, clamp(opacity, 0.0, 0.96));
}

float weather_star_field(vec3 dir) {
    if (dir.y <= 0.02) {
        return 0.0;
    }
    // A stable spherical-ish hash grid. It is deliberately sparse and
    // high-frequency: stars are points of light, not another cloud texture.
    vec2 projected = dir.xz / max(dir.y, 0.08) * 95.0;
    vec2 cell = floor(projected);
    vec2 local = fract(projected) - 0.5;
    float seed = weather_hash21(cell);
    float point = 1.0 - smoothstep(0.0, 0.035, length(local));
    float rare = smoothstep(0.992, 1.0, seed);
    float bright = mix(0.45, 1.0, weather_hash21(cell + 17.0));
    return rare * point * bright;
}

vec3 weather_sky_details(vec3 sky, vec3 dir, float elevation, float cloud_occlusion) {
    if (params.depth_params.x <= 0.5) {
        return sky;
    }
    // sun_dir.y is positive while the sun is above the horizon and is the
    // canonical day/night signal already used by the TOD system.
    float night = 1.0 - smoothstep(-0.08, 0.20, params.sun_dir.y);
    float sky_visibility = 1.0 - clamp(cloud_occlusion, 0.0, 1.0);
    float stars = weather_star_field(dir) * night * sky_visibility;
    sky += params.weather_sky.rgb * stars;

    // At night WTHR's SKY_SUN colour is the authored moon tint in the legacy
    // weather table. Keep the moon direction deterministic when the engine's
    // below-horizon sun sentinel has no horizontal component.
    vec3 moon_direction = vec3(-params.sun_dir.x, 0.18, -params.sun_dir.z);
    if (length(moon_direction.xz) < 0.05) {
        moon_direction = vec3(0.46, 0.28, 0.82);
    }
    moon_direction = normalize(moon_direction);
    float moon_cos = dot(dir, moon_direction);
    float moon_edge = 0.9992;
    if (moon_cos > moon_edge && elevation > 0.0) {
        float moon_disc = smoothstep(moon_edge, 1.0, moon_cos);
        sky += params.sun_color.rgb * moon_disc
            * params.weather_lightning.w * night * 0.65 * sky_visibility;
    }

    float aurora = params.weather_aurora.x * night
        * smoothstep(0.12, 0.48, elevation);
    if (aurora > 0.0) {
        float travel = params.weather_aurora.y > 0.5
            ? params.weather_params.w * 0.018
            : 0.0;
        float bands = 0.5 + 0.5 * sin(dir.x * 17.0 + dir.z * 5.0 + travel);
        float curtains = 0.5 + 0.5 * sin(dir.z * 31.0 - dir.x * 7.0 + bands * 2.0);
        vec3 aurora_color = mix(vec3(0.08, 0.42, 0.28), vec3(0.18, 0.35, 0.75), curtains);
        sky += aurora_color * aurora * bands * curtains * 0.38 * sky_visibility;
    }

    return sky;
}

vec3 weather_precipitation(vec3 color, vec2 uv) {
    if (params.depth_params.x <= 0.5) {
        return color;
    }
    float time = params.weather_params.w;
    float wind_speed = params.weather_wind.y;
    vec2 wind = params.weather_wind.xz;

    // Rain is a coherent screen-space field: every streak advects in the
    // authored wind direction, while a perpendicular term gives the slanted
    // fall seen in gusts. It is a presentation overlay for distant rain;
    // authored/local particle emitters remain responsible for close impacts.
    vec2 rain_grid = uv * vec2(150.0, 90.0);
    vec2 rain_cell = floor(rain_grid);
    vec2 rain_local = fract(rain_grid);
    float rain_seed = weather_hash21(rain_cell);
    vec2 rain_drift = wind * time * (0.11 + wind_speed * 0.23);
    float rain_y = fract(rain_seed + time * (0.42 + wind_speed * 0.8));
    float rain_x = fract(rain_seed * 7.13 + rain_drift.x + rain_local.y * 0.18);
    float rain_line = 1.0 - smoothstep(0.012, 0.0,
        abs(rain_local.x - rain_x + wind.x * 0.018));
    float rain_mask = smoothstep(0.52, 0.96, rain_seed);
    float rain = rain_line * rain_mask * params.weather_params.x;

    // Snow uses larger, slower, round flakes and only a small wind-driven
    // fall vector. Keeping this separate from rain is important: sharing the
    // streak primitive makes a snow storm read as translucent rain.
    vec2 snow_grid = uv * vec2(62.0, 42.0);
    vec2 snow_cell = floor(snow_grid);
    vec2 snow_local = fract(snow_grid);
    float snow_seed = weather_hash21(snow_cell + 91.7);
    vec2 snow_pos = fract(vec2(snow_seed, snow_seed * 5.7)
        + vec2(wind.x * time * 0.06, time * 0.075));
    float flake = 1.0 - smoothstep(0.0, 0.095, length(snow_local - snow_pos));
    float snow = flake * smoothstep(0.72, 0.98, snow_seed)
        * params.weather_params.y;

    vec3 precipitation_color = vec3(0.65, 0.78, 0.95) * rain
        + vec3(0.92, 0.96, 1.0) * snow;
    float precipitation_alpha = clamp(rain * 0.28 + snow * 0.24, 0.0, 0.55);
    color = mix(color, color + precipitation_color, precipitation_alpha);

    // Thunder is a sparse, deterministic flash. The event phase is seeded
    // per burst so frequency controls do not turn into a hard metronome.
    float burst_rate = 0.12 + params.weather_params.z * 2.2;
    float burst_id = floor(time * burst_rate);
    float burst_phase = fract(time * burst_rate);
    float burst_seed = weather_hash21(vec2(burst_id, 37.1));
    float flash = (1.0 - smoothstep(0.0, 0.045, burst_phase))
        * step(0.64, burst_seed)
        * params.weather_params.z;
    color += params.weather_lightning.rgb * flash * 0.32;
    return color;
}

// Compute sky color from view direction.
vec3 compute_sky(vec3 dir) {
    vec3 zenith = params.sky_zenith.xyz;
    vec3 horizon = params.sky_horizon.xyz;
    float sun_size = params.sky_zenith.w;
    float sun_intensity = params.sun_dir.w;
    // Host promises `params.sun_dir.xyz` is already normalised
    // (per `SkyParams::sun_direction` doc — "normalized, world-space
    // Y-up"). The pre-fix `normalize(...)` per fragment was wasted
    // compute on the composite fullscreen draw. See REN-D10-NEW-07
    // (audit 2026-05-09). If the host contract ever weakens, the
    // dot-product / sun-disc maths below silently degrade — re-add
    // the normalize at that point and fix the SkyParams comment.
    vec3 sun_direction = params.sun_dir.xyz;
    vec3 sun_col = params.sun_color.xyz;

    // Elevation: 0 at horizon, 1 at zenith. Clamp negative (below horizon)
    // to a slightly darkened horizon for a ground-plane approximation.
    float elevation = dir.y;

    // Sky gradient: smooth blend from horizon to zenith.
    // Use a non-linear curve so the horizon band is wider (more natural).
    float t = clamp(elevation, 0.0, 1.0);
    t = sqrt(t); // widen horizon band
    vec3 sky = mix(horizon, zenith, t);

    // Below-horizon darkening: ground approximation (not a ground
    // plane, just a colour fade toward the WTHR-authored ground
    // tint). #541 — pre-fix this branch faked the ground colour as
    // `horizon * 0.3` and dropped the authored `SKY_LOWER` group
    // entirely. The real Sky-Lower colour ships per-TOD on every
    // exterior WTHR, so the night ground is appropriately dark and
    // the sunrise / sunset fringe inherits the warm authored tint
    // without compositor-side tweaking.
    if (elevation < 0.0) {
        float below = clamp(-elevation * 3.0, 0.0, 1.0);
        sky = mix(horizon, params.sky_lower.xyz, below);
    }

    // Broad cloud body first; authored WTHR layers below add their original
    // silhouettes and colour variation without being solely responsible for
    // sky occupancy. Accumulate opacity so celestial objects remain behind
    // both representations instead of painting over cloud cover.
    vec4 procedural_cloud = weather_procedural_cloud(sky, dir, elevation, sun_direction);
    sky = mix(sky, procedural_cloud.rgb, procedural_cloud.a);
    float cloud_occlusion = procedural_cloud.a;

    // Cloud layer 0 (from WTHR cloud_textures[0]).
    //
    // Project the upper hemisphere onto an infinite horizontal plane
    // overhead: uv = (dir.xz / dir.y) × tile_scale. This gives perspective-
    // correct foreshortening at low elevations (clouds at the horizon look
    // stretched and tile densely, directly overhead they look large and
    // slow-moving) without needing a real dome mesh.
    //
    // cloud_params.z == 0 disables the sample so the checkerboard fallback
    // handle is never read on cells without WTHR cloud data.
    // Analytic mip LOD: as elevation → 0 the UV magnitude grows as 1/elevation,
    // so the mip should rise by log2(1/elevation). Factor 0.5 keeps the transition
    // gentler than the raw log2 slope. textureLod bypasses the driver's dFdx/dFdy
    // estimate, which would see a 100x–500x UV discontinuity across horizon-fade
    // quads and snap to mip-0 (per-texel aliasing visible in #730). SH-13.
    float cloud_lod = log2(1.0 / max(elevation, 0.05)) * 0.5;

    float tile_scale = params.cloud_params.z;
    if (tile_scale > 0.0 && elevation > 0.0) {
        uint cloud_idx = floatBitsToUint(params.cloud_params.w);
        // max() floor guards against the overhead singularity (dir.y → 0)
        // producing NaN UVs. 0.05 matches ~3° of remaining foreshortening.
        vec2 uv = dir.xz / max(elevation, 0.05) * tile_scale
                + params.cloud_params.xy;
        vec4 cloud = textureLod(textures[nonuniformEXT(cloud_idx)], uv, cloud_lod);
        // Fade clouds out at the horizon so the projection singularity
        // doesn't produce an ugly stretched band right at elevation=0.
        float horizon_fade = smoothstep(0.0, 0.12, elevation);
        vec4 tint = params.cloud_tint_0;
        cloud.rgb *= tint.rgb;
        float layer_alpha = cloud.a * tint.a * horizon_fade;
        sky = mix(sky, cloud.rgb, layer_alpha);
        cloud_occlusion = 1.0 - (1.0 - cloud_occlusion) * (1.0 - layer_alpha);
    }

    // Cloud layer 1 (WTHR CNAM — higher-altitude deck, opposite drift direction).
    // tile_scale_1 == 0.0 when no CNAM texture was loaded; the branch is
    // skipped entirely so the bindless array is never sampled with index 0.
    float tile_scale_1 = params.cloud_params_1.z;
    if (tile_scale_1 > 0.0 && elevation > 0.0) {
        uint cloud_idx_1 = floatBitsToUint(params.cloud_params_1.w);
        vec2 uv_1 = dir.xz / max(elevation, 0.05) * tile_scale_1
                  + params.cloud_params_1.xy;
        vec4 cloud_1 = textureLod(textures[nonuniformEXT(cloud_idx_1)], uv_1, cloud_lod);
        float horizon_fade_1 = smoothstep(0.0, 0.12, elevation);
        vec4 tint_1 = params.cloud_tint_1;
        cloud_1.rgb *= tint_1.rgb;
        float layer_alpha_1 = cloud_1.a * tint_1.a * horizon_fade_1;
        sky = mix(sky, cloud_1.rgb, layer_alpha_1);
        cloud_occlusion = 1.0 - (1.0 - cloud_occlusion) * (1.0 - layer_alpha_1);
    }

    // Cloud layer 2 (WTHR ANAM, M33.1) — same projection / fade as layer 1.
    float tile_scale_2 = params.cloud_params_2.z;
    if (tile_scale_2 > 0.0 && elevation > 0.0) {
        uint cloud_idx_2 = floatBitsToUint(params.cloud_params_2.w);
        vec2 uv_2 = dir.xz / max(elevation, 0.05) * tile_scale_2
                  + params.cloud_params_2.xy;
        vec4 cloud_2 = textureLod(textures[nonuniformEXT(cloud_idx_2)], uv_2, cloud_lod);
        float horizon_fade_2 = smoothstep(0.0, 0.12, elevation);
        vec4 tint_2 = params.cloud_tint_2;
        cloud_2.rgb *= tint_2.rgb;
        float layer_alpha_2 = cloud_2.a * tint_2.a * horizon_fade_2;
        sky = mix(sky, cloud_2.rgb, layer_alpha_2);
        cloud_occlusion = 1.0 - (1.0 - cloud_occlusion) * (1.0 - layer_alpha_2);
    }

    // Cloud layer 3 (WTHR BNAM, M33.1) — same projection / fade as layer 1.
    float tile_scale_3 = params.cloud_params_3.z;
    if (tile_scale_3 > 0.0 && elevation > 0.0) {
        uint cloud_idx_3 = floatBitsToUint(params.cloud_params_3.w);
        vec2 uv_3 = dir.xz / max(elevation, 0.05) * tile_scale_3
                  + params.cloud_params_3.xy;
        vec4 cloud_3 = textureLod(textures[nonuniformEXT(cloud_idx_3)], uv_3, cloud_lod);
        float horizon_fade_3 = smoothstep(0.0, 0.12, elevation);
        vec4 tint_3 = params.cloud_tint_3;
        cloud_3.rgb *= tint_3.rgb;
        float layer_alpha_3 = cloud_3.a * tint_3.a * horizon_fade_3;
        sky = mix(sky, cloud_3.rgb, layer_alpha_3);
        cloud_occlusion = 1.0 - (1.0 - cloud_occlusion) * (1.0 - layer_alpha_3);
    }

    // Sun disc: bright circular spot with a soft edge.
    // sun_size is cos(half-angle) of the disc — lower = wider.
    // Use a smooth transition band outside the core to avoid hard edges
    // from screen-space direction reconstruction precision.
    //
    // `elevation > 0.0` matches the cloud-layer gate convention above
    // and stops the disc painting over the below-horizon ground tint
    // at sunset/sunrise (the `mix(horizon, params.sky_lower.xyz, below)`
    // in `compute_sky` produces a "ground" colour that the disc would
    // otherwise overwrite). #800.
    float cos_angle = dot(dir, sun_direction);
    float sun_edge_start = sun_size - 0.002; // soft outer fringe
    if (cos_angle > sun_edge_start && elevation > 0.0) {
        float t = (cos_angle - sun_edge_start) / (1.0 - sun_edge_start);
        t = smoothstep(0.0, 1.0, t);
        // Core is bright, edge fades smoothly.
        float core = smoothstep(sun_size, 1.0, cos_angle);
        float disc = mix(t * 0.5, 1.0, core);

        // #478 — when CLMT FNAM ships a sun sprite (non-zero index),
        // sample it within the disc and multiply by sun_col; otherwise
        // fall back to the flat sun_col (pre-fix behaviour). The UV
        // comes from projecting `dir` onto a tangent plane
        // perpendicular to `sun_direction` and scaling so the texture
        // fills the disc radius.
        uint sun_tex_idx = floatBitsToUint(params.sun_color.w);
        vec3 disc_color = sun_col;
        if (sun_tex_idx != 0u) {
            // Local 2D basis on the plane perpendicular to sun_direction.
            vec3 up_world = abs(sun_direction.y) < 0.99
                ? vec3(0.0, 1.0, 0.0)
                : vec3(0.0, 0.0, 1.0);
            vec3 tangent = normalize(cross(up_world, sun_direction));
            vec3 bitangent = cross(sun_direction, tangent);

            // Disc radius in tangent-plane units: `sqrt(1 - sun_size^2)`
            // matches the angular half-width on the unit sphere. We
            // normalise by this so the sprite fills the disc exactly.
            float disc_r = sqrt(max(0.0, 1.0 - sun_size * sun_size));
            vec2 uv = vec2(dot(dir, tangent), dot(dir, bitangent)) / max(disc_r, 1e-4);
            uv = uv * 0.5 + 0.5;
            // Force mip 0. Default `texture()` uses derivative-based
            // mip selection which goes badly wrong here: the UV is
            // divided by `disc_r` (~0.017 for a ~1° wide sun) so
            // adjacent-pixel UV deltas are ~0.06 even though both
            // pixels sit inside a 100-pixel-wide disc. The sampler
            // then picks mip 4-5 of a 256×256 sprite and the sun
            // renders as ~8 visible texels (~16 pixels each — see
            // the user-reported screenshot, ByroRedux | 1 FPS frame
            // 2026-05-24). The sprite is supposed to look sharp
            // regardless of disc screen-size; mip 0 + bilinear gives
            // ~2.5 source texels per output pixel at typical disc
            // widths, which is supersampling (sharp, no aliasing).
            // Sub-pixel discs at very large render distances would
            // alias on mip 0, but the disc is bright enough that
            // small-disc aliasing is invisible against `sun_intensity`.
            vec4 sprite = textureLod(textures[nonuniformEXT(sun_tex_idx)], uv, 0.0);
            disc_color = sun_col * sprite.rgb;
        }

        float sun_visibility = 1.0 - clamp(cloud_occlusion, 0.0, 1.0) * 0.94;
        sky += disc_color * sun_intensity * params.weather_sky.w * disc * sun_visibility;
    }

    // Sun glow: soft radial halo around the sun.
    //
    // #799 — multiply by `sun_intensity` so the halo fades with the
    // disc through the day/night ramp. Pre-fix the disc faded
    // correctly (its `sky += disc_color * sun_intensity * disc`
    // already carried the factor) but the halo stayed at constant 0.15 *
    // sun_col, so a WTHR with non-zero `SKY_SUN[NIGHT]` (e.g.
    // Skyrim's MoonShadow) painted a faint warm halo at midnight.
    //
    // Falloff tightened to `pow(., 8)` × 0.10 (was `pow(., 4)` × 0.15)
    // on the Markarth 2026-05-10 probe. The wider 4-power halo at
    // `sun_intensity = 4` was adding +0.28 RGB to the sky ~33° off the
    // sun direction; ACES tonemap then pushed the entire visible
    // upper hemisphere to pale-white in any view including the sun's
    // half of the sky. The `pow(., 8)` curve concentrates the halo
    // to ~15° around the disc — preserves the bright sun region
    // without washing the rest of the sky.
    float glow = max(cos_angle, 0.0);
    glow = pow(glow, 8.0);
    float glow_visibility = 1.0 - clamp(cloud_occlusion, 0.0, 1.0) * 0.82;
    sky += sun_col * glow * 0.10 * sun_intensity * params.weather_sky.w * glow_visibility;

    return weather_sky_details(sky, dir, elevation, cloud_occlusion);
}

void main() {
    outReactive = 0.0;
    outTransparency = 0.0;
    vec4 direct4 = texture(hdrTex, fragUV);
    vec3 direct = direct4.rgb;

    // Correctness oracles are already final in the main-pass direct
    // attachment. Do not let caustics, fog, volumetrics, bloom, or dither
    // turn transport visibility/energy into a different question.
    uint dbgFlags = floatBitsToUint(params.depth_params.y);
    uint debugMode = floatBitsToUint(params.depth_params.z);
    if (debugMode != RENDER_DEBUG_LEGACY_FLAGS
        && debugMode > RENDER_DEBUG_MODE_MAX)
    {
        outColor = vec4(1.0, 0.0, 1.0, 1.0);
        return;
    }
    // #2978 — the "which views are oracles" policy is generated into
    // shader_constants.glsl from DBG_VIZ_RAW_OUTPUT_ANY/_ALL, the same two
    // catalogs shader_constants.rs's debug_viz_requires_raw_output walks. Do
    // not re-spell its clauses here: that is what let the Rust side and both
    // shaders drift apart behind a four-literal subset check.
    bool rawDebug = debugMode == RENDER_DEBUG_LEGACY_FLAGS
        ? DBG_VIZ_REQUIRES_RAW_OUTPUT(dbgFlags)
        : (debugMode != RENDER_DEBUG_FINAL
            && debugMode != RENDER_DEBUG_COMPOSITE_TERM
            && debugMode != RENDER_DEBUG_VOLUMETRIC_TERM);
    if (rawDebug) {
        outColor = direct4;
        return;
    }

    // Depth is a classification signal here, not a continuously filtered
    // colour. Fetch the exact render-resolution texel so a geometry/clear
    // edge cannot be bilinearly blended into the wrong branch.
    //
    // The depth attachment is cleared to exactly 1.0. Do not use an
    // epsilon such as the old 0.9999 sentinel: with the engine's 0.1 / 300k
    // projection that value is already reached at ~997 game units (~14 m in
    // FO4), so valid geometry beyond that distance was mistaken for empty
    // depth and lost its direct + indirect lighting in this pass.
    float depth = texelFetch(depthTex, ivec2(gl_FragCoord.xy), 0).r;
    bool has_surface = depth < 1.0;
    bool is_sky = !has_surface && (params.depth_params.x > 0.5);

    // REN-D8-02 / REN-D16-02 — bloom and the volumetric/height-fog term
    // used to be folded into `combined` only inside the (former) geometry
    // branch below, so a plain `if (is_sky) { ...; return; }` skipped both
    // for sky pixels: no bloom on bright sun/sky highlights, and fog that
    // stopped dead at the horizon/geometry silhouette instead of extending
    // into the sky. `combined` is now built by either branch and both
    // terms are applied once, after, to whichever value each branch
    // produced.
    vec3 combined;
    if (is_sky) {
        // Sky pixel: reconstruct view direction and compute sky color.
        //
        // #2466 / REN-D8-N01 — composite the sky BEHIND the main pass
        // result rather than instead of it. Blend pipelines run with
        // `depth_write_enable(false)`, so an alpha-blended fragment with
        // nothing opaque behind it leaves depth at the cleared 1.0 and
        // lands in this branch. Pre-fix `combined = compute_sky(dir)`
        // dropped `direct4.rgb` outright, so every translucent draw
        // silhouetted purely against open sky vanished — smoke / steam /
        // magic billboards, alpha-blended banners, glass panes on a
        // skyline. (The FSR masks were never lost, so FSR was being told
        // a transparent surface was there after its colour had been
        // erased.)
        //
        // `direct4.a` is the accumulated coverage lane
        // (`pipeline::coverage_alpha_factors`): 0 where nothing drew,
        // the over-operator coverage for classic alpha blends, and
        // untouched by additive FX — which contribute through `direct`
        // without occluding the sky, exactly as their `dst = ONE`
        // equation says. `direct` is already premultiplied against the
        // transparent-black clear the host uses whenever this branch is
        // live (`draw.rs::hdr_clear`), so it adds in directly.
        //
        // #2920 / REN-D8-01 — restore the INDIRECT half of the same fix.
        // #2466 above rescued `direct` for these fragments but left the
        // demodulated GI term behind: this branch never read `indirectTex`
        // / `albedoTex`, so the identical surface one pixel to the side —
        // over opaque geometry, taking the `else` arm — got
        // `indirect * albedo` added while this one did not. The visible
        // result was a brightness discontinuity along the silhouette
        // wherever a LIT alpha-blended draw crosses the horizon (cloth
        // banners, hanging signs, lit alpha-blended card geometry). Draws
        // that early-out with `outRawIndirect = vec4(0.0)` — the
        // effect-shader / `MAT_FLAG_EFFECT_SOFT` arm, `MATERIAL_KIND_NO_LIGHTING`,
        // and both glass exits — are unaffected either way, which is why the
        // gap survived: the most common sky-silhouetted draws zero the term
        // anyway.
        //
        // Deliberately CONSISTENT with the geometry arm, not exact: the
        // demodulated reassembly `indirect * albedo` is not linear in the
        // blend operator, so over the transparent-black clear the product
        // carries coverage twice (`coverage²·(I·A)`). Matching the `else`
        // arm is the smaller and safer change; making it exact would mean
        // dividing the premultiply out once — and only once — on both arms.
        vec3 dir = screen_to_world_dir(fragUV);
        float coverage = clamp(direct4.a, 0.0, 1.0);
        vec3 skyIndirect = texture(indirectTex, fragUV).rgb;
        vec3 skyAlbedo = texture(albedoTex, fragUV).rgb;
        combined = compute_sky(dir) * (1.0 - coverage)
            + direct
            + skyIndirect * skyAlbedo;
    } else {
        // Geometry pixel: combine direct + (indirect × albedo) and tone map.
        // The shader wrote lighting-only indirect (no local albedo) so
        // SVGF operates on a texture-free signal; multiply here to
        // re-apply surface color. See #268.
        vec3 indirect = texture(indirectTex, fragUV).rgb;
        vec3 albedo = texture(albedoTex, fragUV).rgb;

        // Caustic (#321): refracted-light scatter from the caustic_splat
        // pass. Stored as fixed-point RGB in three R32_UINT array layers;
        // decode here and scale by the receiver's own albedo. This preserves
        // both the transmitting glass hue and the receiving material color.
        //
        // #1257 / Phase E of #1210 — sum the water-side caustic
        // accumulator alongside the glass-/MultiLayerParallax-side
        // one. Both writers share `CAUSTIC_FIXED_SCALE` (the
        // generated `#define` in `shader_constants.glsl`) so their
        // fixed-point sums are on a unified radiance basis. Water remains a
        // scalar white contribution and is added equally to all channels.
        // Composite and these accumulators are render-resolution resources.
        // Convert normalized UV to a clamped render pixel so integer fetches
        // remain well-defined at the right and bottom edges.
        ivec2 causticSize = textureSize(causticTex, 0).xy;
        ivec2 causticPixel = clamp(
            ivec2(fragUV * vec2(causticSize)),
            ivec2(0),
            causticSize - ivec2(1)
        );
        vec3 glassCausticRaw = vec3(
            texelFetch(causticTex, ivec3(causticPixel, 0), 0).r,
            texelFetch(causticTex, ivec3(causticPixel, 1), 0).r,
            texelFetch(causticTex, ivec3(causticPixel, 2), 0).r);
        // #2508 — when the water-side accumulator isn't live this session,
        // binding 8 (waterCausticTex) is fallback-bound to the SAME view as
        // binding 5 (causticTex); sampling it would double-count the glass
        // caustic contribution instead of contributing zero. Gate the read
        // on the host-set flag rather than skip the fetch conditionally —
        // texelFetch has no side effects, so a uniform branch here compiles
        // to a select, not real divergence.
        uint waterCausticRaw = params.caustic_flags.x > 0.5
            ? texelFetch(waterCausticTex, causticPixel, 0).r
            : 0u;
        // #1575 — promote each accumulator to float BEFORE the add so the sum
        // can't wrap u32. Each raw can independently climb toward the
        // 0xFFFFFFFF per-deposit ceiling (caustic_splat.comp clamps each
        // deposit, not the running sum of the two textures); adding two large
        // uints wraps mod 2^32 to ~0 → a black pixel the post-divide firefly
        // cap cannot recover.
        vec3 causticRadiance = (glassCausticRaw + vec3(float(waterCausticRaw)))
            / CAUSTIC_FIXED_SCALE;
        // Firefly cap on the COMBINED caustic radiance (TARGET 2). The focal
        // cusp under glass spheres / water sums thousands of forward-splat
        // deposits (imageAtomicAdd) into a few pixels; under camera motion the
        // caustic accumulator is cleared per-frame (no EMA smoothing), so the
        // un-averaged cusp peak flickers as bright splotches. Bound the peak
        // before it enters `combined`. Indirect-only: `direct` is added
        // separately below, so the light source is untouched. Pre-ACES linear
        // ceiling — start conservative and tune down per the TARGET 2 bench.
        const float CAUSTIC_FIREFLY_MAX = 16.0;
        causticRadiance = min(causticRadiance, vec3(CAUSTIC_FIREFLY_MAX));
        vec3 caustic = albedo * causticRadiance;

        combined = direct + indirect * albedo + caustic;
    }

    float fogTransmittance = 1.0;
    vec4 sampledVolume = vec4(0.0, 0.0, 0.0, 1.0);

    // M55 Phase 3 — volumetric modulation via single sampler3D tap.
    // The volumetric pipeline pre-integrates `(∫inscatter, T_cum)`
    // along the view ray per froxel column in a compute pass; here
    // we just look up the value at the fragment's depth slice and
    // modulate `combined`. Done in HDR-linear (pre-ACES) per
    // Frostbite §5.3 so the tone-mapper sees the inscattered
    // radiance and the scene together.
    //
    // The volumetric volume is screen-space in XY and hybrid linear /
    // exponential in Z. Preserve a single XY ray column while interpolating
    // between cumulative depth slices; unconditional XY filtering crosses
    // opaque structure boundaries and creates wall leaks.
    //
    // REN-D8-02 / REN-D16-02 — gated on `has_surface || is_sky`, not
    // `has_surface` alone. `depth == 1.0` still reconstructs a valid
    // far-plane `worldPos` through the same `inv_view_proj` math
    // `screen_to_world_dir` uses for sky rays, so the froxel tap and the
    // analytic beyond-grid continuation both resolve correctly for sky
    // pixels too. The one case still excluded — no surface AND not sky
    // (an interior cell's unmodelled void, `depth_params.x <= 0.5`) —
    // has no meaningful world position to integrate fog along.
    if (has_surface || is_sky) {
        vec2 ndc_xy = fragUV * 2.0 - 1.0;
        vec4 clip = vec4(ndc_xy, depth, 1.0);
        vec4 world = params.inv_view_proj * clip;
        vec3 worldPos = world.xyz / max(abs(world.w), 1.0e-6);
        float worldDist = length(worldPos - params.camera_pos.xyz);
        float gridFar = params.volume_params.x;
        float slice = hybridSliceCoordinate(min(worldDist, gridFar));
        // #2470 — `volumetrics_integrate.comp` writes the post-slab
        // cumulative state into texel `i` at normalized depth
        // `(i+1)/N` (the slab's BACK face), but `sampler3D` places
        // texel `i`'s filtered center at `(i+0.5)/N`. Sampling
        // `hybridSliceCoordinate`'s raw depth directly lands halfway
        // into the NEXT slab, over-applying about half a slab of
        // fog everywhere. Remap the back-face-convention depth onto
        // the texel-center grid before the tap.
        float sliceCount = max(params.sky_horizon.w, 1.0);
        float sliceTexel = clamp((slice * sliceCount - 0.5) / sliceCount, 0.0, 1.0);
        vec4 vol = sampleVolumetricColumn(fragUV, sliceTexel, depth);
        sampledVolume = vol;
        // vol.rgb = ∫inscatter accumulated 0..slice (HDR-linear)
        // vol.a   = cumulative transmittance through 0..slice
        //
        // `params.depth_params.z` mirrors that host-side const, so
        // it's always 1.0 here; `vol.a` genuinely carries cumulative
        // transmittance and `vol.rgb` in-scattered radiance. Frostbite
        // §5.3 standard form: attenuate FIRST (energy lost to
        // absorption between camera and fragment), then ADD inscatter
        // (radiance that arrived via in-scattering, NOT itself
        // attenuated by `T_cum` — the integrate pass already weighted
        // each slab's contribution by its own running transmittance).
        combined = combined * vol.a + vol.rgb;
        fogTransmittance *= vol.a;

        // Beyond-grid aerial perspective. Start at the grid boundary so
        // this composes after the froxel integral without double-counting.
        // The exact horizontal branch lives in heightFogOpticalDepth.
        if (worldDist > gridFar && params.height_fog_params.w > 0.5) {
            vec3 rayDir = (worldPos - params.camera_pos.xyz)
                / max(worldDist, 1.0e-6);
            vec3 segmentOrigin = params.camera_pos.xyz + rayDir * gridFar;
            // REN-D16-01 / #2225 — baseHeight anchors to the ground/floor
            // near the camera (params.camera_pos.w), not the camera's own
            // eye height, so fog thins with real altitude instead of
            // following the player vertically.
            float tau = heightFogOpticalDepth(
                params.height_fog_params.x,
                segmentOrigin.y,
                rayDir.y,
                worldDist - gridFar,
                params.camera_pos.w,
                params.height_fog_params.y
            );
            float transmittance = exp(-min(tau, 80.0));

            // Continue from the grid's own boundary radiance rather than
            // restarting with a flat `fog_color * albedo`. The froxel integral
            // and this tail are two different models of the same medium: the
            // grid's `vol.rgb` is real in-scattered radiance (sun, sky, light
            // injection, phase function), while a flat authored colour is not.
            // Restarting made distant geometry — the only geometry past
            // `gridFar` — shade differently from everything inside the grid,
            // which shows up as the mountains changing appearance when the
            // grid's reach changes. Measured on an FNV vista, moving
            // `--fog-grid-far-m` 128 -> 512 shifted the distant ridge by up to
            // 117/255 while every in-grid pixel stayed identical.
            //
            // `vol.rgb / (1 - vol.a)` is the opacity-weighted average source
            // radiance the grid resolved, so handing it to the tail makes the
            // two agree at the seam by construction. Falls back to the authored
            // colour when the grid carried too little opacity for that ratio to
            // mean anything, and is clamped so a bright near-field froxel
            // (a fire in view) cannot bleed into the aerial term.
            vec3 authoredRadiance = params.fog_color.rgb
                * params.height_fog_params.z;
            float gridOpacity = 1.0 - clamp(vol.a, 0.0, 1.0);
            vec3 sourceRadiance = authoredRadiance;
            if (gridOpacity > 0.02) {
                vec3 gridRadiance = vol.rgb / gridOpacity;
                // Bound the continuation to the authored energy scale; the
                // grid can hold local emitters the distant medium does not.
                float authoredLuma = max(dot(authoredRadiance, vec3(0.2126, 0.7152, 0.0722)), 1.0e-4);
                float gridLuma = max(dot(gridRadiance, vec3(0.2126, 0.7152, 0.0722)), 0.0);
                float scale = min(1.0, (authoredLuma * 4.0) / max(gridLuma, 1.0e-4));
                sourceRadiance = gridRadiance * scale;
            }
            vec3 aerial = sourceRadiance * (1.0 - transmittance);
            combined = combined * transmittance + aerial;
            fogTransmittance *= transmittance;
        }
    }

    if (debugMode == RENDER_DEBUG_VOLUMETRIC_TERM) {
        // Isolate the integrated froxel field from surfaces, analytic
        // beyond-grid fog, bloom, exposure, and grading. Exponential mapping
        // makes HDR emission inspectable in a raw correctness view; opacity
        // supplies a neutral floor so cold smoke remains visible too.
        vec3 mappedRadiance = vec3(1.0)
            - exp(-max(sampledVolume.rgb, vec3(0.0)));
        float opacity = clamp(1.0 - sampledVolume.a, 0.0, 1.0);
        outColor = vec4(max(mappedRadiance, vec3(opacity)), 1.0);
        return;
    }

    // Underwater god rays. The authored submersion extinction is already
    // computed from each game's WATR fog range on the CPU, so use it as the
    // gate/energy budget rather than inventing a second water-depth model.
    // A narrow sun-alignment lobe gives shafts toward the visible sun, while
    // the depth ramp keeps the effect negligible at the waterline. This is a
    // screen-space presentation term intentionally kept after the integrated
    // froxel debug return and before bloom; it requires no new descriptor.
    if (params.underwater.w > 0.0 && params.sun_dir.w > 0.0) {
        vec3 viewDir = screen_to_world_dir(fragUV);
        vec3 sunDirection = normalize(params.sun_dir.xyz);
        float sunAlignment = max(dot(viewDir, sunDirection), 0.0);
        float shaftLobe = pow(sunAlignment, 18.0);
        float underwaterDistance = has_surface
            ? linearViewDepth(depth)
            : params.volume_params.x;
        float depthRamp = 1.0 - exp(-max(underwaterDistance, 0.0) * 0.002);
        float shaftStrength = shaftLobe * depthRamp
            * clamp(params.underwater.w, 0.0, 0.85)
            * params.sun_dir.w * 0.12;
        vec3 shaftColor = mix(
            params.underwater.rgb,
            params.sun_color.rgb,
            0.35
        );
        combined += shaftColor * shaftStrength;
    }

    // Weather precipitation and lightning are exterior-only presentation
    // terms. Rain/snow is intentionally applied after the volumetric resolve
    // so the streaks remain legible through a deep storm volume, while the
    // shared exterior gate keeps sealed interiors dry.
    if (params.depth_params.x > 0.5) {
        combined = weather_precipitation(combined, fragUV);
    }

    // M58 — bloom add. #2796 / REN-D16-01 moved this OUT of composite:
    // bloom now dispatches AFTER this pass, reading this shader's own
    // assembled `combined` (sky + demodulated GI + caustics + direct)
    // back from the scene image instead of the pre-composite raw HDR,
    // which never contained sky/GI/caustics — those only ever existed in
    // `combined` here. `bloomTex` (binding 7) is therefore unused by this
    // shader now; left declared (not renumbered) so `bloom_views` stays
    // wired through `CompositePipeline`'s existing descriptor-set
    // machinery unchanged. See `bloom.rs::apply_to_scene` for the actual
    // scene-plus-bloom add, now performed in place on this pass's own
    // output.
    if (debugMode == RENDER_DEBUG_COMPOSITE_TERM) {
        // Final render-resolution linear composite: direct + denoised
        // indirect/albedo + caustics + volumetrics/fog, before stochastic
        // dither, temporal reconstruction, exposure or grading. #2796 /
        // REN-D16-01 — bloom is NOT included here any more (it now runs
        // downstream of this pass, see `bloom.rs::apply_to_scene`), so
        // this debug view no longer doubles as a scene+bloom preview.
        outColor = vec4(max(combined, vec3(0.0)), direct4.a);
        return;
    }
    combined += vec3(preResolveDither());
    float fogOpacity = clamp(1.0 - fogTransmittance, 0.0, 1.0);
    // Fog has no coherent surface motion. Route its coverage through the
    // transparency/composition mask and conservatively flag dense fog as
    // reactive so FSR does not lock onto the geometry behind it.
    outTransparency = fogOpacity;
    outReactive = smoothstep(0.35, 0.8, fogOpacity) * 0.9;

    // Pass `direct4.a` through (mirroring the pre-fix geometry branch) so
    // the alpha-blend marker bit `DEN-6 / #676` preserves through TAA
    // consistently across both sky and geometry pixels. #2466 sharpened
    // what that lane means: it is the accumulated transparent coverage of
    // the pixel (`pipeline::coverage_alpha_factors`), zero on an
    // untouched sky pixel and non-zero exactly where translucent geometry
    // drew — which is what the sky branch above now weighs
    // `compute_sky()` against. Forwarding it symmetrically from both
    // branches keeps the "alpha is the marker, branch on it the same way"
    // contract rather than an asymmetric "1.0 = sky" one. DEN-11.
    outColor = vec4(combined, direct4.a);
}
