//! `spt_recon` — corpus-driven reverse-engineering harness for
//! SpeedTree `.spt` binaries.
//!
//! Walks one or more BSAs, captures per-file stats for every `.spt`,
//! buckets them by leading 16-byte signature, and emits a Markdown
//! report. Pipe the output into `crates/spt/docs/format-notes.md` to
//! grow the running observation log without typing it by hand.
//!
//! ## Usage
//!
//! ```text
//! cargo run -p byroredux-spt --features recon --example spt_recon -- \
//!     "/mnt/data/SteamLibrary/steamapps/common/Fallout New Vegas/Data/Fallout - Meshes.bsa" \
//!     "/mnt/data/SteamLibrary/steamapps/common/Fallout 3 goty/Data/Fallout - Meshes.bsa" \
//!     "/mnt/data/SteamLibrary/steamapps/common/Oblivion/Data/Oblivion - Meshes.bsa"
//! ```
//!
//! ## What you get
//!
//! For each archive: a per-archive subsection with a Markdown
//! aggregate table (file count, size min/median/max, magic16 prefix,
//! sample path) and a sample of printable strings observed across
//! that bucket. The Markdown is checked-in-friendly — drop it under
//! a dated heading in `format-notes.md`.

use byroredux_bsa::BsaArchive;
use byroredux_spt::recon::{Aggregate, FileStats};
use std::path::PathBuf;

fn main() {
    let args: Vec<String> = std::env::args().skip(1).collect();
    if args.is_empty() {
        eprintln!(
            "usage: spt_recon <bsa-path> [<bsa-path>...]\n\
             walks each archive, captures every `.spt` file, and emits a\n\
             Markdown aggregate summary keyed by leading 16-byte signature."
        );
        std::process::exit(2);
    }

    println!("# SpeedTree `.spt` recon — generated by `spt_recon`\n");

    for archive_path in &args {
        let archive = match BsaArchive::open(archive_path) {
            Ok(a) => a,
            Err(e) => {
                eprintln!("[skip] {}: {}", archive_path, e);
                continue;
            }
        };
        let stem = PathBuf::from(archive_path)
            .file_name()
            .map(|s| s.to_string_lossy().into_owned())
            .unwrap_or_else(|| archive_path.clone());
        println!("## `{}`\n", stem);

        let mut agg = Aggregate::default();
        let mut spt_files: Vec<String> = archive
            .list_files()
            .into_iter()
            .filter(|f| f.to_ascii_lowercase().ends_with(".spt"))
            .map(|f| f.to_string())
            .collect();
        spt_files.sort();

        println!("- {} `.spt` file(s) in archive", spt_files.len());
        if spt_files.is_empty() {
            println!();
            continue;
        }

        let mut errors = 0usize;
        for path in &spt_files {
            match archive.extract(path) {
                Ok(bytes) => {
                    let stats = FileStats::capture(path, &bytes);
                    agg.insert(stats);
                }
                Err(e) => {
                    errors += 1;
                    eprintln!("[err] {}: {}", path, e);
                }
            }
        }
        println!(
            "- captured {}/{} files ({} extract errors); total {} bytes\n",
            agg.total_files,
            spt_files.len(),
            errors,
            agg.total_bytes,
        );

        println!("### Buckets by leading 16-byte signature\n");
        println!("{}", agg.render_markdown_table());

        println!("### Strings sampled per bucket\n");
        for (magic, bucket) in &agg.buckets {
            let magic_hex: String = magic.iter().map(|b| format!("{:02x}", b)).collect();
            println!("- `{}` ({} files):", magic_hex, bucket.count);
            if bucket.strings.is_empty() {
                println!("  - _no printable runs ≥ 8 chars observed_");
            } else {
                for s in &bucket.strings {
                    println!("  - `{}`", s);
                }
            }
        }
        println!();
    }
}
