//! `spt_transitions` — corpus-wide tag-transition analyzer.
//!
//! Companion to `spt_tagmap`, with a different premise. Instead of
//! walking the file as a TLV stream and classifying each tag's payload
//! a priori (which fails when a tag's payload length isn't 4 bytes —
//! see `spt_tagmap` notes around tag 2002), this scans EVERY position
//! in the file for tag-shaped u32 values and records the per-tag
//! transition table:
//!
//! ```text
//! (current_tag, byte_distance_to_next_tag, next_tag) → count
//! ```
//!
//! The modal byte distance for each `current_tag` is the empirically
//! observed payload size (including the 4-byte tag itself), so
//! `payload_bytes = mode_distance - 4`. Aggregating across the corpus
//! reveals the full per-tag payload-size table without committing to
//! any one classification heuristic.
//!
//! Tags are deemed plausible if they fall in `[TAG_MIN, TAG_MAX]`,
//! same range as `spt_tagmap`'s parameter section. The geometry tail
//! gets noise rejected automatically because high-tag values
//! (19 985+) and uniformly-zero "tags" don't make it into the
//! transition aggregate.
//!
//! ## Usage
//!
//! ```text
//! cargo run -p byroredux-spt --features recon --example spt_transitions -- \
//!     "/path/to/Fallout - Meshes.bsa" \
//!     "/path/to/Oblivion - Meshes.bsa" \
//!     > /tmp/spt_transitions.md
//! ```

use byroredux_bsa::BsaArchive;
use byroredux_spt::version::MAGIC_HEAD;
use std::collections::{BTreeMap, HashMap};

const TAG_MIN: u32 = 100;
const TAG_MAX: u32 = 13_999;

/// Per-tag aggregated transition table.
#[derive(Default, Debug, Clone)]
struct TagTransitions {
    /// Total occurrences across the corpus.
    total: u32,
    /// `payload_size_bytes → count`. Computed from the byte distance
    /// to the immediately following plausible tag, minus the 4-byte
    /// tag width itself.
    payload_size_histogram: BTreeMap<u32, u32>,
    /// Up to 4 distinct successor tags observed (helps reveal nested
    /// section structures).
    successors: Vec<u32>,
}

impl TagTransitions {
    fn record_transition(&mut self, payload_bytes: u32, next_tag: u32) {
        self.total += 1;
        *self
            .payload_size_histogram
            .entry(payload_bytes)
            .or_insert(0) += 1;
        if self.successors.len() < 8 && !self.successors.contains(&next_tag) {
            self.successors.push(next_tag);
        }
    }

    /// Most-frequent payload size, in bytes.
    fn modal_payload_size(&self) -> Option<u32> {
        self.payload_size_histogram
            .iter()
            .max_by_key(|(_, count)| *count)
            .map(|(size, _)| *size)
    }

    /// True when the modal payload size accounts for ≥ 80 % of all
    /// observations — a "high-confidence" classification.
    fn modal_confidence(&self) -> f32 {
        let modal_count = self
            .payload_size_histogram
            .values()
            .max()
            .copied()
            .unwrap_or(0);
        modal_count as f32 / self.total.max(1) as f32
    }
}

fn main() {
    let archives: Vec<String> = std::env::args().skip(1).collect();
    if archives.is_empty() {
        eprintln!(
            "usage: spt_transitions <bsa-path> [<bsa-path>...]\n\
             scans every aligned position for tag-shaped values and\n\
             aggregates per-tag transition tables to recover payload\n\
             sizes empirically."
        );
        std::process::exit(2);
    }

    let mut transitions: HashMap<u32, TagTransitions> = HashMap::new();
    let mut total_files = 0u32;

    for archive_path in &archives {
        let archive = match BsaArchive::open(archive_path) {
            Ok(a) => a,
            Err(e) => {
                eprintln!("[skip] {}: {}", archive_path, e);
                continue;
            }
        };
        let spt_files: Vec<String> = archive
            .list_files()
            .into_iter()
            .filter(|f| f.to_ascii_lowercase().ends_with(".spt"))
            .map(|f| f.to_string())
            .collect();
        for path in &spt_files {
            let bytes = match archive.extract(path) {
                Ok(b) => b,
                Err(e) => {
                    eprintln!("[err] {} :: {}: {}", archive_path, path, e);
                    continue;
                }
            };
            total_files += 1;
            scan_one_file(&bytes, &mut transitions);
        }
    }

    // Sort by tag value for stable output.
    let mut sorted: Vec<(u32, TagTransitions)> = transitions.into_iter().collect();
    sorted.sort_by_key(|(t, _)| *t);

    println!("# `.spt` per-tag payload-size table\n");
    println!(
        "Generated by `spt_transitions` over {} files. Tag-shaped\n\
         u32 values within `[{}, {}]` collected at every byte offset;\n\
         payload size is the modal distance to the next tag minus 4\n\
         (the tag width itself). High `confidence` = classification\n\
         is reliable enough to wire into the parser.\n",
        total_files, TAG_MIN, TAG_MAX,
    );
    println!(
        "| tag | hex | total | modal payload (bytes) | confidence | \
         payload-size histogram | sample successors |"
    );
    println!("|---:|---:|---:|---:|---:|---|---|");
    for (tag, t) in &sorted {
        let modal = t
            .modal_payload_size()
            .map(|s| s.to_string())
            .unwrap_or_else(|| "?".to_string());
        let conf = (t.modal_confidence() * 100.0).round() as u32;
        let hist: String = t
            .payload_size_histogram
            .iter()
            .map(|(size, n)| format!("{}B×{}", size, n))
            .collect::<Vec<_>>()
            .join(", ");
        let succ: String = t
            .successors
            .iter()
            .take(6)
            .map(|s| s.to_string())
            .collect::<Vec<_>>()
            .join(", ");
        println!(
            "| {} | 0x{:04x} | {} | {} | {}% | {} | {} |",
            tag, tag, t.total, modal, conf, hist, succ,
        );
    }
}

/// Scan a single file: at every offset starting at `MAGIC_HEAD.len()`,
/// record any 4-byte u32 in `[TAG_MIN, TAG_MAX]` as a tag candidate.
/// For each candidate, find the next plausible tag within the next
/// `MAX_PAYLOAD_BYTES` and record the transition.
fn scan_one_file(bytes: &[u8], transitions: &mut HashMap<u32, TagTransitions>) {
    if !bytes.starts_with(MAGIC_HEAD) {
        return;
    }
    /// Maximum payload size we'll consider when looking for a successor
    /// tag. SpeedTree curve text blobs can run ~160 bytes; bounding
    /// at 1024 is generous. We cap to keep noise low.
    const MAX_PAYLOAD_BYTES: usize = 1024;

    // Collect (offset, tag) pairs from the parameter section. Stop
    // when the first u32 outside [TAG_MIN, TAG_MAX] is encountered
    // — same cut-off as `spt_tagmap`. The walker advances 1 byte at a
    // time so we don't miss tags whose payload sizes aren't 4-byte
    // multiples.
    let mut tag_positions: Vec<(usize, u32)> = Vec::new();
    let mut i = MAGIC_HEAD.len();
    while i + 4 <= bytes.len() {
        let v = u32::from_le_bytes([bytes[i], bytes[i + 1], bytes[i + 2], bytes[i + 3]]);
        if (TAG_MIN..=TAG_MAX).contains(&v) {
            tag_positions.push((i, v));
            // Skip ahead by 4 bytes — assume tags don't overlap.
            i += 4;
        } else {
            i += 1;
        }
    }

    // For each tag, the byte distance to the next tag in the same file
    // is the payload size + 4 (tag width). We only count transitions
    // where the next tag is within MAX_PAYLOAD_BYTES of the current
    // one — anything further is noise.
    for win in tag_positions.windows(2) {
        let (off_a, tag_a) = win[0];
        let (off_b, tag_b) = win[1];
        let distance = off_b.saturating_sub(off_a);
        if distance > MAX_PAYLOAD_BYTES {
            continue;
        }
        let payload_bytes = (distance as u32).saturating_sub(4);
        transitions
            .entry(tag_a)
            .or_default()
            .record_transition(payload_bytes, tag_b);
    }
}
