//! Build script — generates `shaders/include/shader_constants.glsl` from
//! `src/shader_constants_data.rs` (the single source of truth).
//!
//! Every GLSL shader that needs these constants should add:
//!   `#include "include/shader_constants.glsl"`
//!
//! and be compiled with:
//!   glslangValidator -V -I crates/renderer/shaders <shader.glsl> -o <shader.glsl>.spv

use std::fmt::Write as FmtWrite;
use std::path::Path;

// Pull the same constants that shader_constants.rs uses. Because build.rs
// runs in a separate compilation context it cannot import from the crate, so
// we share the raw data file via include!.
include!("src/shader_constants_data.rs");

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=src/shader_constants_data.rs");

    let mut out = String::new();
    writeln!(out, "// AUTO-GENERATED by crates/renderer/build.rs — DO NOT EDIT").unwrap();
    writeln!(out, "// Source of truth: crates/renderer/src/shader_constants_data.rs").unwrap();
    writeln!(out, "// Regenerate:   cargo build -p byroredux-renderer").unwrap();
    writeln!(out, "// Then recompile shaders: glslangValidator -V -I crates/renderer/shaders <shader>").unwrap();
    writeln!(out, "//").unwrap();
    writeln!(out, "// Integer #defines carry the `u` suffix (uint literals); floats always").unwrap();
    writeln!(out, "// have a decimal point. Workgroup-size #defines omit the suffix so they").unwrap();
    writeln!(out, "// work in layout(local_size_x = WORKGROUP_X) qualifiers.").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "// Cluster grid").unwrap();
    writeln!(out, "#define CLUSTER_TILES_X {CLUSTER_TILES_X}u").unwrap();
    writeln!(out, "#define CLUSTER_TILES_Y {CLUSTER_TILES_Y}u").unwrap();
    writeln!(out, "#define CLUSTER_SLICES_Z {CLUSTER_SLICES_Z}u").unwrap();
    writeln!(out, "#define CLUSTER_NEAR {CLUSTER_NEAR:?}").unwrap();
    writeln!(out, "#define CLUSTER_FAR_FLOOR {CLUSTER_FAR_FLOOR:?}").unwrap();
    writeln!(out, "#define CLUSTER_FAR_FALLBACK {CLUSTER_FAR_FALLBACK:?}").unwrap();
    writeln!(out, "#define MAX_LIGHTS_PER_CLUSTER {MAX_LIGHTS_PER_CLUSTER}u").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "// Vertex layout (global SSBO)").unwrap();
    writeln!(out, "#define VERTEX_STRIDE_FLOATS {VERTEX_STRIDE_FLOATS}u").unwrap();
    writeln!(out, "#define VERTEX_UV_OFFSET_FLOATS {VERTEX_UV_OFFSET_FLOATS}u").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "// Skinning").unwrap();
    writeln!(out, "#define MAX_BONES_PER_MESH {MAX_BONES_PER_MESH}u").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "// Glass / IOR ray budget").unwrap();
    writeln!(out, "#define GLASS_RAY_BUDGET {GLASS_RAY_BUDGET}u").unwrap();
    writeln!(out, "#define GLASS_RAY_COST {GLASS_RAY_COST}u").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "// Caustic accumulation").unwrap();
    writeln!(out, "#define CAUSTIC_FIXED_SCALE {CAUSTIC_FIXED_SCALE:?}").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "// Compute workgroup sizes (bloom, volumetrics, SSAO, TAA).").unwrap();
    writeln!(out, "// Used in layout(local_size_x = WORKGROUP_X, ...) — no `u` suffix.").unwrap();
    writeln!(out, "#define WORKGROUP_X {WORKGROUP_X}").unwrap();
    writeln!(out, "#define WORKGROUP_Y {WORKGROUP_Y}").unwrap();
    writeln!(out, "#define WORKGROUP_Z {WORKGROUP_Z}").unwrap();

    let out_path = Path::new("shaders/include/shader_constants.glsl");
    if let Some(parent) = out_path.parent() {
        std::fs::create_dir_all(parent).expect("failed to create shaders/include/");
    }

    let current = std::fs::read_to_string(out_path).unwrap_or_default();
    if current != out {
        std::fs::write(out_path, &out).expect("failed to write shader_constants.glsl");
        println!("cargo:warning=Regenerated shaders/include/shader_constants.glsl — recompile affected GLSL shaders.");
    }
}
