//! Build script — generates `shaders/include/shader_constants.glsl` from
//! `src/shader_constants_data.rs` (the single source of truth).
//!
//! Every GLSL shader that needs these constants should add:
//!   `#include "include/shader_constants.glsl"`
//!
//! and be compiled with:
//!   glslangValidator -V -I crates/renderer/shaders <shader.glsl> -o <shader.glsl>.spv

use std::fmt::Write as FmtWrite;
use std::path::Path;

// Pull the same constants that shader_constants.rs uses. Because build.rs
// runs in a separate compilation context it cannot import from the crate, so
// we share the raw data file via include!.
include!("src/shader_constants_data.rs");

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=src/shader_constants_data.rs");

    let mut out = String::new();
    writeln!(
        out,
        "// AUTO-GENERATED by crates/renderer/build.rs — DO NOT EDIT"
    )
    .unwrap();
    writeln!(
        out,
        "// Source of truth: crates/renderer/src/shader_constants_data.rs"
    )
    .unwrap();
    writeln!(out, "// Regenerate:   cargo build -p byroredux-renderer").unwrap();
    writeln!(
        out,
        "// Then recompile shaders: glslangValidator -V -I crates/renderer/shaders <shader>"
    )
    .unwrap();
    writeln!(out, "//").unwrap();
    writeln!(
        out,
        "// Integer #defines carry the `u` suffix (uint literals); floats always"
    )
    .unwrap();
    writeln!(
        out,
        "// have a decimal point. Workgroup-size #defines omit the suffix so they"
    )
    .unwrap();
    writeln!(
        out,
        "// work in layout(local_size_x = WORKGROUP_X) qualifiers."
    )
    .unwrap();
    writeln!(out).unwrap();

    writeln!(out, "// Cluster grid").unwrap();
    writeln!(out, "#define CLUSTER_TILES_X {CLUSTER_TILES_X}u").unwrap();
    writeln!(out, "#define CLUSTER_TILES_Y {CLUSTER_TILES_Y}u").unwrap();
    writeln!(out, "#define CLUSTER_SLICES_Z {CLUSTER_SLICES_Z}u").unwrap();
    writeln!(out, "#define CLUSTER_NEAR {CLUSTER_NEAR:?}").unwrap();
    writeln!(out, "#define CLUSTER_FAR_FLOOR {CLUSTER_FAR_FLOOR:?}").unwrap();
    writeln!(out, "#define CLUSTER_FAR_FALLBACK {CLUSTER_FAR_FALLBACK:?}").unwrap();
    writeln!(
        out,
        "#define MAX_LIGHTS_PER_CLUSTER {MAX_LIGHTS_PER_CLUSTER}u"
    )
    .unwrap();
    writeln!(out).unwrap();

    writeln!(out, "// Vertex layout (global SSBO)").unwrap();
    writeln!(out, "#define VERTEX_STRIDE_FLOATS {VERTEX_STRIDE_FLOATS}u").unwrap();
    writeln!(
        out,
        "#define VERTEX_NORMAL_OFFSET_FLOATS {VERTEX_NORMAL_OFFSET_FLOATS}u"
    )
    .unwrap();
    writeln!(
        out,
        "#define VERTEX_UV_OFFSET_FLOATS {VERTEX_UV_OFFSET_FLOATS}u"
    )
    .unwrap();
    writeln!(out).unwrap();

    writeln!(out, "// Skinning").unwrap();
    writeln!(out, "#define MAX_BONES_PER_MESH {MAX_BONES_PER_MESH}u").unwrap();
    // No `u` suffix — used in `layout(local_size_x = SKIN_WORKGROUP_SIZE)`.
    writeln!(out, "#define SKIN_WORKGROUP_SIZE {SKIN_WORKGROUP_SIZE}").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "// Material kind enum (`GpuMaterial.materialKind`).").unwrap();
    writeln!(
        out,
        "// Authoritative values: scene_buffer/constants.rs. #1401."
    )
    .unwrap();
    writeln!(out, "#define MATERIAL_KIND_GLASS {MATERIAL_KIND_GLASS}u").unwrap();
    writeln!(
        out,
        "#define MATERIAL_KIND_EFFECT_SHADER {MATERIAL_KIND_EFFECT_SHADER}u"
    )
    .unwrap();
    writeln!(
        out,
        "#define MATERIAL_KIND_NO_LIGHTING {MATERIAL_KIND_NO_LIGHTING}u"
    )
    .unwrap();
    writeln!(out, "#define SHADOW_MASK_OPAQUE {SHADOW_MASK_OPAQUE}u").unwrap();
    writeln!(out, "#define SHADOW_MASK_GLASS {SHADOW_MASK_GLASS}u").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "// Glass / IOR ray budget").unwrap();
    writeln!(out, "#define GLASS_RAY_BUDGET {GLASS_RAY_BUDGET}u").unwrap();
    writeln!(out, "#define GLASS_RAY_COST {GLASS_RAY_COST}u").unwrap();
    writeln!(out).unwrap();

    writeln!(
        out,
        "// One-bounce GI light cap (shadow ray per light at a bounce hit)"
    )
    .unwrap();
    writeln!(out, "#define GI_HIT_LIGHT_CAP {GI_HIT_LIGHT_CAP}u").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "// Caustic accumulation").unwrap();
    writeln!(out, "#define CAUSTIC_FIXED_SCALE {CAUSTIC_FIXED_SCALE:?}").unwrap();
    writeln!(out).unwrap();

    writeln!(
        out,
        "// Compute workgroup sizes (bloom, volumetrics, SSAO, TAA)."
    )
    .unwrap();
    writeln!(
        out,
        "// Used in layout(local_size_x = WORKGROUP_X, ...) — no `u` suffix."
    )
    .unwrap();
    writeln!(out, "#define WORKGROUP_X {WORKGROUP_X}").unwrap();
    writeln!(out, "#define WORKGROUP_Y {WORKGROUP_Y}").unwrap();
    writeln!(out, "#define WORKGROUP_Z {WORKGROUP_Z}").unwrap();
    writeln!(out).unwrap();

    writeln!(
        out,
        "// Clustered light culling thread count (no `u` suffix — used in"
    )
    .unwrap();
    writeln!(out, "// `layout(local_size_x = THREADS_PER_CLUSTER)`).").unwrap();
    writeln!(out, "#define THREADS_PER_CLUSTER {THREADS_PER_CLUSTER}").unwrap();
    writeln!(out).unwrap();

    writeln!(
        out,
        "// Bloom + volumetrics tunables (floats — always decimal)."
    )
    .unwrap();
    writeln!(out, "#define BLOOM_INTENSITY {BLOOM_INTENSITY:?}").unwrap();
    writeln!(out, "#define VOLUME_FAR {VOLUME_FAR:?}").unwrap();
    writeln!(out).unwrap();

    writeln!(
        out,
        "// Per-instance flag bits (`GpuInstance.flags`, lower 16 bits)."
    )
    .unwrap();
    writeln!(
        out,
        "// Authoritative values: scene_buffer/constants.rs. #1190."
    )
    .unwrap();
    writeln!(
        out,
        "#define INSTANCE_FLAG_NON_UNIFORM_SCALE {INSTANCE_FLAG_NON_UNIFORM_SCALE}u"
    )
    .unwrap();
    writeln!(
        out,
        "#define INSTANCE_FLAG_ALPHA_BLEND {INSTANCE_FLAG_ALPHA_BLEND}u"
    )
    .unwrap();
    writeln!(
        out,
        "#define INSTANCE_FLAG_CAUSTIC_SOURCE {INSTANCE_FLAG_CAUSTIC_SOURCE}u"
    )
    .unwrap();
    writeln!(
        out,
        "#define INSTANCE_FLAG_TERRAIN_SPLAT {INSTANCE_FLAG_TERRAIN_SPLAT}u"
    )
    .unwrap();
    writeln!(
        out,
        "#define INSTANCE_RENDER_LAYER_SHIFT {INSTANCE_RENDER_LAYER_SHIFT}u"
    )
    .unwrap();
    writeln!(
        out,
        "#define INSTANCE_RENDER_LAYER_MASK {INSTANCE_RENDER_LAYER_MASK}u"
    )
    .unwrap();
    writeln!(
        out,
        "#define INSTANCE_FLAG_FLAT_SHADING {INSTANCE_FLAG_FLAT_SHADING}u"
    )
    .unwrap();
    writeln!(
        out,
        "#define INSTANCE_FLAG_DIFFUSE_ALPHA {INSTANCE_FLAG_DIFFUSE_ALPHA}u"
    )
    .unwrap();
    writeln!(out).unwrap();

    writeln!(
        out,
        "// Per-material flag bits (`GpuMaterial.materialFlags`)."
    )
    .unwrap();
    writeln!(
        out,
        "// Authoritative values: vulkan/material.rs `material_flag::*`. #1190."
    )
    .unwrap();
    writeln!(
        out,
        "#define MAT_FLAG_VERTEX_COLOR_EMISSIVE {MAT_FLAG_VERTEX_COLOR_EMISSIVE}u"
    )
    .unwrap();
    writeln!(out, "#define MAT_FLAG_EFFECT_SOFT {MAT_FLAG_EFFECT_SOFT}u").unwrap();
    writeln!(
        out,
        "#define MAT_FLAG_EFFECT_PALETTE_COLOR {MAT_FLAG_EFFECT_PALETTE_COLOR}u"
    )
    .unwrap();
    writeln!(
        out,
        "#define MAT_FLAG_EFFECT_PALETTE_ALPHA {MAT_FLAG_EFFECT_PALETTE_ALPHA}u"
    )
    .unwrap();
    writeln!(out, "#define MAT_FLAG_EFFECT_LIT {MAT_FLAG_EFFECT_LIT}u").unwrap();
    // Bits 5-9 — Disney BSDF / SSS / model-space-normals suite (#1285).
    writeln!(out, "#define MAT_FLAG_PBR_BSDF {MAT_FLAG_PBR_BSDF}u").unwrap();
    writeln!(
        out,
        "#define MAT_FLAG_TRANSLUCENCY {MAT_FLAG_TRANSLUCENCY}u"
    )
    .unwrap();
    writeln!(
        out,
        "#define MAT_FLAG_MODEL_SPACE_NORMALS {MAT_FLAG_MODEL_SPACE_NORMALS}u"
    )
    .unwrap();
    writeln!(
        out,
        "#define MAT_FLAG_TRANSLUCENCY_THICK_OBJECT {MAT_FLAG_TRANSLUCENCY_THICK_OBJECT}u"
    )
    .unwrap();
    writeln!(
        out,
        "#define MAT_FLAG_TRANSLUCENCY_MIX_ALBEDO {MAT_FLAG_TRANSLUCENCY_MIX_ALBEDO}u"
    )
    .unwrap();
    // Lighting-influence byte-field shift (#890 Stage 2).
    writeln!(
        out,
        "#define MAT_FLAG_EFFECT_LI_SHIFT {MAT_FLAG_EFFECT_LI_SHIFT}u"
    )
    .unwrap();
    // NOTE: `material_flag::BGSM_AUTHORED` is intentionally NOT emitted
    // here. The shader is format-agnostic — BGSM-specific translation
    // happens in `merge_bgsm_into_mesh` (writes `metalness_override` /
    // `roughness_override` on Material), so the shader never branches
    // on material provenance. Flag still rides on the Rust side for
    // debug-server inspection. See `feedback_format_translation.md`.
    writeln!(out).unwrap();

    writeln!(
        out,
        "// Normal-alpha-as-spec marker bit (OR'd into `GpuMaterial.glossMapIndex`)."
    )
    .unwrap();
    writeln!(
        out,
        "#define NORMAL_ALPHA_SPEC_BIT {NORMAL_ALPHA_SPEC_BIT}u"
    )
    .unwrap();
    writeln!(out).unwrap();

    writeln!(
        out,
        "// Water motion-kind enum (matches `byroredux::cell_loader::water::WaterKind`)."
    )
    .unwrap();
    writeln!(out, "#define WATER_CALM {WATER_CALM}u").unwrap();
    writeln!(out, "#define WATER_RIVER {WATER_RIVER}u").unwrap();
    writeln!(out, "#define WATER_RAPIDS {WATER_RAPIDS}u").unwrap();
    writeln!(out, "#define WATER_WATERFALL {WATER_WATERFALL}u").unwrap();
    writeln!(out).unwrap();

    writeln!(
        out,
        "// Debug-viz bit flags (set via console for renderer bisects)."
    )
    .unwrap();
    // #1860 — emit driven from the shared DBG_BITS catalog (defined
    // alongside the constants above) instead of one hand-written
    // `writeln!` per bit, so a newly-added DBG_* constant can no longer
    // ship its header emit without also being covered by the
    // value-pin / no-redeclare / count-parity tests in shader_constants.rs.
    for (name, value) in DBG_BITS {
        writeln!(out, "#define {name} {value}u").unwrap();
    }
    writeln!(out).unwrap();

    writeln!(
        out,
        "// #1799 / PERF-D5-NEW-01 — compile-time gate for the legacy 16-slot"
    )
    .unwrap();
    writeln!(
        out,
        "// WRS reservoir arrays. 0 (default): preprocessed out of"
    )
    .unwrap();
    writeln!(
        out,
        "// triangle.frag entirely. 1: restores the pre-fix always-compiled"
    )
    .unwrap();
    writeln!(
        out,
        "// behavior for A/B against ReSTIR (requires a shader recompile)."
    )
    .unwrap();
    writeln!(out, "#define ENABLE_LEGACY_WRS {ENABLE_LEGACY_WRS}").unwrap();

    let out_path = Path::new("shaders/include/shader_constants.glsl");
    if let Some(parent) = out_path.parent() {
        std::fs::create_dir_all(parent).expect("failed to create shaders/include/");
    }

    let current = std::fs::read_to_string(out_path).unwrap_or_default();
    if current != out {
        std::fs::write(out_path, &out).expect("failed to write shader_constants.glsl");
        println!("cargo:warning=Regenerated shaders/include/shader_constants.glsl — recompile affected GLSL shaders.");
    }
}
