//! `HostState` — the store data every WIT host call is dispatched against.

use super::*;

pub(crate) struct HostState {
    pub(crate) principal: Principal,
    pub(crate) grants: CapabilitySet,
    pub(crate) catalog: Arc<ServiceCatalog>,
    pub(crate) limits: StoreLimits,
    pub(crate) logs: Vec<LogEntry>,
    pub(crate) log_bytes: usize,
    pub(crate) max_log_entries: usize,
    pub(crate) max_log_message_bytes: usize,
    pub(crate) max_log_bytes: usize,
    /// Set when a log was refused for budget rather than for content (#3050),
    /// so `ModInstance::enter` can attribute the resulting trap. Cleared by
    /// the reader.
    pub(crate) log_budget_exhausted: bool,
    pub(crate) schemas: Vec<ComponentSchemaDeclaration>,
    pub(crate) subscribed_to_activate: bool,
    pub(crate) subscribed_to_cell_load: bool,
    pub(crate) subscribed_to_hit: bool,
    pub(crate) subscribed_to_equipment: bool,
    pub(crate) subscribed_to_input: bool,
    pub(crate) subscribed_to_session: bool,
    pub(crate) custom_subscriptions: Vec<EventId>,
    pub(crate) legacy_mod_event_callbacks: BTreeMap<EventId, String>,
    pub(crate) legacy_mod_event_builders: LegacySkseModEventBuilders,
    pub(crate) legacy_containers: LegacyContainerRegistry,
    pub(crate) current_custom_event: Option<CustomEvent>,
    pub(crate) current_legacy_callback: Option<String>,
    pub(crate) current_console_args: Option<Vec<u8>>,
    pub(crate) console_command_indices: std::collections::BTreeSet<u32>,
    pub(crate) script_functions: BTreeMap<u32, ScriptFunctionDeclaration>,
    pub(crate) current_script_arguments: Option<Vec<ScriptValue>>,
    pub(crate) current_script_result: Option<ScriptValue>,
    pub(crate) console_output: Vec<String>,
    pub(crate) console_output_bytes: usize,
    pub(crate) console_failed: bool,
    pub(crate) console_output_budget_exhausted: bool,
    pub(crate) subscribed_to_update: bool,
    pub(crate) principal_storage_schema: Option<u32>,
    pub(crate) principal_storage: BTreeMap<StorageKey, PrincipalStorageValue>,
    pub(crate) entity_projections: BTreeMap<byroredux_sdk::identity::EntityRef, EntityProjection>,
    pub(crate) spatial_snapshot: Arc<SpatialSnapshot>,
    pub(crate) content_catalog: Arc<ContentCatalog>,
    pub(crate) faction_relationships: Arc<FactionRelationshipCatalog>,
    pub(crate) engine_settings: Arc<SettingsSnapshot>,
    pub(crate) setting_declarations: Vec<SettingDeclaration>,
    pub(crate) pending_commands: Vec<HostCommand>,
    pub(crate) max_commands_per_entry: usize,
    pub(crate) accepting_commands: bool,
    pub(crate) command_budget_exhausted: bool,
}
