//! Built-in Bethesda event names (Skyrim + Fallout 4 + Starfield union),
//! used to classify a decompiled `.pex` function as an `Event` vs a
//! `Function` — mirroring Champollion's `writeFunction` rule (name starts
//! with `on` AND is a known engine event name).
//!
//! GENERATED from Champollion's `Decompiler/EventNames.hpp` (the three
//! per-game `EventNames` lists, lowercased + deduplicated into one union).
//! #4471 — Champollion's frozen lists are themselves incomplete (its
//! Starfield-era union predates shipped engine events), so this list is a
//! superset: engine events vanilla base-class scripts implement but
//! Champollion omits (census in the issue — `OnAttach`,
//! `OnShipCruiseArrival`, `OnUnconscious`, …) are added by hand. New
//! entries must be real engine events (implemented in base-class scripts),
//! lowercased, and inserted in sorted position — the sorted+dedup guard
//! fails otherwise.

/// Sorted, lowercase built-in event names. Sorted so [`is_event_name`] can
/// binary-search.
pub(crate) const EVENT_NAMES: &[&str] = &[
    "onaction",
    "onactivate",
    "onactoractivatedref",
    "onactorvaluechanged",
    "onactorvaluegreaterthan",
    "onactorvaluelessthan",
    "onaffinityevent",
    "onaffinityeventsent",
    "onaliaschanged",
    "onaliasinit",
    "onaliasreset",
    "onaliasshutdown",
    "onaliasstarted",
    "onanimationevent",
    "onanimationeventunregistered",
    "onattach",
    "onattachedtocell",
    "onbegin",
    "onbeginstate",
    "onbuildermenuselect",
    "oncellattach",
    "oncelldetach",
    "oncellload",
    "onchallengecompleted",
    "onchange",
    "onclose",
    "oncombatlistadded",
    "oncombatlistremoved",
    "oncombatstatechanged",
    "oncommandmodecompletecommand",
    "oncommandmodeenter",
    "oncommandmodeexit",
    "oncommandmodegivecommand",
    "oncompaniondismiss",
    "onconsciousnessstatechanged",
    "oncontainerchanged",
    "oncontroldown",
    "oncontrolup",
    "oncrewassigned",
    "oncrewdismissed",
    "oncripple",
    "ondeath",
    "ondeferredkill",
    "ondestroyed",
    "ondestructionstagechanged",
    "ondetachedfromcell",
    "ondifficultychanged",
    "ondistancegreaterthan",
    "ondistancelessthan",
    "ondying",
    "oneffectfinish",
    "oneffectstart",
    "onend",
    "onendstate",
    "onenterbleedout",
    "onenterfurniture",
    "onenteroutpostbeaconmode",
    "onentershipinterior",
    "onentersneaking",
    "onentryrun",
    "onequipped",
    "onescortwaitstart",
    "onescortwaitstop",
    "onexitfurniture",
    "onexitshipinterior",
    "onfurnitureevent",
    "ongainlos",
    "ongameplayoptionchanged",
    "ongetup",
    "ongrab",
    "onhit",
    "onholotapechatter",
    "onholotapeplay",
    "onhomeshipset",
    "oninit",
    "onitemadded",
    "onitemequipped",
    "onitemremoved",
    "onitemunequipped",
    "onkeydown",
    "onkeyup",
    "onkill",
    "onload",
    "onlocationchange",
    "onlocationcleared",
    "onlocationexplored",
    "onlocationloaded",
    "onlockstatechanged",
    "onlooksmenuevent",
    "onlostlos",
    "onlycanthropystatechanged",
    "onmagiceffectapply",
    "onmapmarkerdiscovered",
    "onmenuitemrun",
    "onmenuopencloseevent",
    "onmissionaccepted",
    "onobjectdestroyed",
    "onobjectequipped",
    "onobjectrepaired",
    "onobjectunequipped",
    "onopen",
    "onoutpostitempoweroff",
    "onoutpostitempoweron",
    "onoutpostplaced",
    "onpackagechange",
    "onpackageend",
    "onpackagestart",
    "onpartialcripple",
    "onphasebegin",
    "onphaseend",
    "onpicklock",
    "onpickpocketfailed",
    "onpipboyradiodetection",
    "onplanetsiteselectevent",
    "onplayerarrested",
    "onplayerassaultactor",
    "onplayerbowshot",
    "onplayerbuyship",
    "onplayercamerastate",
    "onplayercompleteresearch",
    "onplayercraftitem",
    "onplayercreaterobot",
    "onplayercrimegold",
    "onplayerdialoguetarget",
    "onplayerentervertibird",
    "onplayerfailedplotroute",
    "onplayerfalllongdistance",
    "onplayerfasttravel",
    "onplayerfasttravelend",
    "onplayerfireweapon",
    "onplayerfollowerwarp",
    "onplayerhealteammate",
    "onplayeritemadded",
    "onplayerjail",
    "onplayerloadgame",
    "onplayerloiteringbegin",
    "onplayerloiteringend",
    "onplayermodarmorweapon",
    "onplayermodifiedship",
    "onplayermodrobot",
    "onplayermurderactor",
    "onplayerpayfine",
    "onplayerplanetsurveycomplete",
    "onplayerscannedobject",
    "onplayerscanplanet",
    "onplayersellship",
    "onplayership",
    "onplayersleepstart",
    "onplayersleepstop",
    "onplayerswimming",
    "onplayerteleport",
    "onplayertrespass",
    "onplayeruseworkbench",
    "onplayerwaitstart",
    "onplayerwaitstop",
    "onpoweroff",
    "onpoweron",
    "onquestinit",
    "onquestrejected",
    "onquestshutdown",
    "onqueststarted",
    "onquesttimerend",
    "onquesttimermod",
    "onquesttimerpause",
    "onquesttimerresume",
    "onquesttimerstart",
    "onquickcontaineropened",
    "onraceswitchcomplete",
    "onradiationdamage",
    "onread",
    "onrecoverfrombleedout",
    "onrelease",
    "onreset",
    "onscanned",
    "onsell",
    "onshipbought",
    "onshipcruisearrival",
    "onshipdock",
    "onshipfartravel",
    "onshipgravjump",
    "onshiplanding",
    "onshiprampdown",
    "onshiprefueled",
    "onshipscan",
    "onshipsold",
    "onshipsystemdamaged",
    "onshipsystempowerchange",
    "onshipsystemrepaired",
    "onshiptakeoff",
    "onshipundock",
    "onsit",
    "onsleepstart",
    "onsleepstop",
    "onspaceshipcombatlistadded",
    "onspaceshipcombatlistremoved",
    "onspeechchallengeavailable",
    "onspeechchallengecompletion",
    "onspellcast",
    "onstageset",
    "onstarmaptargetselectevent",
    "onstart",
    "onstoryactivateactor",
    "onstoryactorattach",
    "onstoryaddtoplayer",
    "onstoryarrest",
    "onstoryassaultactor",
    "onstoryattractionobject",
    "onstorybribenpc",
    "onstorycastmagic",
    "onstorychangelocation",
    "onstorychangelocationex",
    "onstoryclearlocation",
    "onstorycraftitem",
    "onstorycrimegold",
    "onstorycure",
    "onstorydialogue",
    "onstorydiscoverdeadbody",
    "onstoryescapejail",
    "onstoryexploredlocation",
    "onstoryflatternpc",
    "onstoryhackterminal",
    "onstoryhello",
    "onstoryincreaselevel",
    "onstoryincreaseskill",
    "onstoryinfection",
    "onstoryintimidatenpc",
    "onstoryironsights",
    "onstoryjail",
    "onstorykillactor",
    "onstorylocationloaded",
    "onstorymineexplosion",
    "onstorynewvoicepower",
    "onstorypayfine",
    "onstorypicklock",
    "onstorypickpocket",
    "onstorypiracyactor",
    "onstoryplayergetsfavor",
    "onstoryrelationshipchange",
    "onstoryremovefromplayer",
    "onstoryscript",
    "onstoryservedtime",
    "onstoryshipdock",
    "onstoryshiplanding",
    "onstoryspeechchallengecompletion",
    "onstorytrespass",
    "onterminalmenuenter",
    "onterminalmenuitemrun",
    "ontimer",
    "ontimergametime",
    "ontrackedstatsevent",
    "ontranslationalmostcomplete",
    "ontranslationcomplete",
    "ontranslationfailed",
    "ontraphit",
    "ontraphitstart",
    "ontraphitstop",
    "ontrigger",
    "ontriggerenter",
    "ontriggerleave",
    "ontutorialevent",
    "onunconscious",
    "onunequipped",
    "onunload",
    "onupdate",
    "onupdategametime",
    "onvampirefeed",
    "onvampirismstatechanged",
    "onwardhit",
    "onworkshopcargolinkchanged",
    "onworkshopflycam",
    "onworkshopmode",
    "onworkshopnpctransfer",
    "onworkshopobjectdestroyed",
    "onworkshopobjectgrabbed",
    "onworkshopobjectmoved",
    "onworkshopobjectplaced",
    "onworkshopobjectremoved",
    "onworkshopobjectrepaired",
    "onworkshopoutputlink",
];

/// Whether `name` is a built-in engine event (case-insensitive). The
/// caller has already checked the `on` prefix, matching Champollion.
pub(crate) fn is_event_name(name: &str) -> bool {
    let lower = name.to_ascii_lowercase();
    EVENT_NAMES.binary_search(&lower.as_str()).is_ok()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn list_is_sorted_for_binary_search() {
        assert!(EVENT_NAMES.windows(2).all(|w| w[0] < w[1]));
    }

    #[test]
    fn known_events_match_case_insensitively() {
        assert!(is_event_name("OnActivate"));
        assert!(is_event_name("onactivate"));
        assert!(is_event_name("OnInit"));
        assert!(is_event_name("OnUpdate"));
        assert!(!is_event_name("MyHelperFunction"));
        assert!(!is_event_name("OnSomethingNobodyDefined"));
    }

    /// #4471 — Champollion's frozen `EventNames.hpp` is missing engine
    /// events vanilla base-class scripts implement, so handlers for them
    /// decompiled as `Function` instead of `Event` (census: 20 handlers
    /// across 12 names on 26,641 scripts; the vanilla-source typos in the
    /// same census are correctly NOT listed here). Pin all 12.
    #[test]
    fn the_census_engine_events_classify_as_events() {
        for name in [
            "OnAttach",
            "OnStoryClearLocation",
            "OnShipCruiseArrival",
            "OnGameplayOptionChanged",
            "OnUnconscious",
            "OnStoryChangeLocationEx",
            "OnSpaceshipCombatListAdded",
            "OnSpaceshipCombatListRemoved",
            "OnPlayerFastTravel",
            "OnStorySpeechChallengeCompletion",
            "OnPlayerScanPlanet",
            "OnPlayerShip",
        ] {
            assert!(
                is_event_name(name),
                "`{name}` is an engine event (base-class census #4471) and \
                 must classify as an Event"
            );
        }
        // The correctly-demoted vanilla typos stay out of the list.
        assert!(!is_event_name("oncelldetatch"));
    }
}
