// AUTO-GENERATED by crates/renderer/build.rs — DO NOT EDIT
// Source of truth: crates/renderer/src/shader_constants_data.rs
// Regenerate:   cargo build -p byroredux-renderer
// Then recompile shaders: glslangValidator -V -I crates/renderer/shaders <shader>
//
// Integer #defines carry the `u` suffix (uint literals); floats always
// have a decimal point. Workgroup-size #defines omit the suffix so they
// work in layout(local_size_x = WORKGROUP_X) qualifiers.

// Cluster grid
#define CLUSTER_TILES_X 16u
#define CLUSTER_TILES_Y 9u
#define CLUSTER_SLICES_Z 24u
#define CLUSTER_NEAR 0.1
#define CLUSTER_FAR_FLOOR 10000.0
#define CLUSTER_FAR_FALLBACK 50000.0
#define MAX_LIGHTS_PER_CLUSTER 32u

// Vertex layout (global SSBO)
#define VERTEX_STRIDE_FLOATS 25u
#define VERTEX_UV_OFFSET_FLOATS 9u

// Skinning
#define MAX_BONES_PER_MESH 128u

// Glass / IOR ray budget
#define GLASS_RAY_BUDGET 8192u
#define GLASS_RAY_COST 4u

// Caustic accumulation
#define CAUSTIC_FIXED_SCALE 65536.0

// Compute workgroup sizes (bloom, volumetrics, SSAO, TAA).
// Used in layout(local_size_x = WORKGROUP_X, ...) — no `u` suffix.
#define WORKGROUP_X 8
#define WORKGROUP_Y 8
#define WORKGROUP_Z 8
