// AUTO-GENERATED by crates/renderer/build.rs — DO NOT EDIT
// Source of truth: crates/renderer/src/shader_constants_data.rs
// Regenerate:   cargo build -p byroredux-renderer
// Then recompile shaders: glslangValidator -V -I crates/renderer/shaders <shader>
//
// Integer #defines carry the `u` suffix (uint literals); floats always
// have a decimal point. Workgroup-size #defines omit the suffix so they
// work in layout(local_size_x = WORKGROUP_X) qualifiers.

// Cluster grid
#define CLUSTER_TILES_X 16u
#define CLUSTER_TILES_Y 9u
#define CLUSTER_SLICES_Z 24u
#define CLUSTER_NEAR 0.1
#define CLUSTER_FAR_FLOOR 10000.0
#define CLUSTER_FAR_FALLBACK 50000.0
#define MAX_LIGHTS_PER_CLUSTER 32u

// Vertex layout (global SSBO)
#define VERTEX_STRIDE_FLOATS 25u
#define VERTEX_UV_OFFSET_FLOATS 9u

// Skinning
#define MAX_BONES_PER_MESH 128u

// Glass / IOR ray budget
#define GLASS_RAY_BUDGET 8192u
#define GLASS_RAY_COST 4u

// Caustic accumulation
#define CAUSTIC_FIXED_SCALE 65536.0

// Compute workgroup sizes (bloom, volumetrics, SSAO, TAA).
// Used in layout(local_size_x = WORKGROUP_X, ...) — no `u` suffix.
#define WORKGROUP_X 8
#define WORKGROUP_Y 8
#define WORKGROUP_Z 8

// Clustered light culling thread count (no `u` suffix — used in
// `layout(local_size_x = THREADS_PER_CLUSTER)`).
#define THREADS_PER_CLUSTER 32

// Bloom + volumetrics tunables (floats — always decimal).
#define BLOOM_INTENSITY 0.15
#define VOLUME_FAR 200.0

// Water motion-kind enum (matches `byroredux::cell_loader::water::WaterKind`).
#define WATER_CALM 0u
#define WATER_RIVER 1u
#define WATER_RAPIDS 2u
#define WATER_WATERFALL 3u

// Debug-viz bit flags (set via console for renderer bisects).
#define DBG_BYPASS_POM 1u
#define DBG_BYPASS_DETAIL 2u
#define DBG_VIZ_NORMALS 4u
#define DBG_VIZ_TANGENT 8u
#define DBG_BYPASS_NORMAL_MAP 16u
#define DBG_RESERVED_20 32u
#define DBG_VIZ_RENDER_LAYER 64u
#define DBG_VIZ_GLASS_PASSTHRU 128u
#define DBG_DISABLE_SPECULAR_AA 256u
#define DBG_DISABLE_HALF_LAMBERT_FILL 512u
