// AUTO-GENERATED by crates/renderer/build.rs — DO NOT EDIT
// Source of truth: crates/renderer/src/shader_constants_data.rs
// Regenerate:   cargo build -p byroredux-renderer
// Then recompile shaders: glslangValidator -V -I crates/renderer/shaders <shader>
//
// Integer #defines carry the `u` suffix (uint literals); floats always
// have a decimal point. Workgroup-size #defines omit the suffix so they
// work in layout(local_size_x = WORKGROUP_X) qualifiers.

// Cluster grid
#define CLUSTER_TILES_X 16u
#define CLUSTER_TILES_Y 9u
#define CLUSTER_SLICES_Z 24u
#define CLUSTER_NEAR 0.1
#define CLUSTER_FAR_FLOOR 10000.0
#define CLUSTER_FAR_FALLBACK 50000.0
#define MAX_LIGHTS_PER_CLUSTER 128u

// Vertex layout (global SSBO)
#define VERTEX_STRIDE_FLOATS 25u
#define VERTEX_NORMAL_OFFSET_FLOATS 6u
#define VERTEX_UV_OFFSET_FLOATS 9u

// Skinning
#define MAX_BONES_PER_MESH 144u
#define SKIN_WORKGROUP_SIZE 64

// Material kind enum (`GpuMaterial.materialKind`).
// Authoritative values: scene_buffer/constants.rs. #1401.
#define MATERIAL_KIND_GLASS 100u
#define MATERIAL_KIND_EFFECT_SHADER 101u
#define MATERIAL_KIND_NO_LIGHTING 102u

// Glass / IOR ray budget
#define GLASS_RAY_BUDGET 1048576u
#define GLASS_RAY_COST 4u

// One-bounce GI light cap (shadow ray per light at a bounce hit)
#define GI_HIT_LIGHT_CAP 8u

// Caustic accumulation
#define CAUSTIC_FIXED_SCALE 65536.0

// Compute workgroup sizes (bloom, volumetrics, SSAO, TAA).
// Used in layout(local_size_x = WORKGROUP_X, ...) — no `u` suffix.
#define WORKGROUP_X 8
#define WORKGROUP_Y 8
#define WORKGROUP_Z 8

// Clustered light culling thread count (no `u` suffix — used in
// `layout(local_size_x = THREADS_PER_CLUSTER)`).
#define THREADS_PER_CLUSTER 32

// Bloom + volumetrics tunables (floats — always decimal).
#define BLOOM_INTENSITY 0.15
#define VOLUME_FAR 200.0

// Per-instance flag bits (`GpuInstance.flags`, lower 16 bits).
// Authoritative values: scene_buffer/constants.rs. #1190.
#define INSTANCE_FLAG_NON_UNIFORM_SCALE 1u
#define INSTANCE_FLAG_ALPHA_BLEND 2u
#define INSTANCE_FLAG_CAUSTIC_SOURCE 4u
#define INSTANCE_FLAG_TERRAIN_SPLAT 8u
#define INSTANCE_FLAG_FLAT_SHADING 128u
#define INSTANCE_FLAG_DIFFUSE_ALPHA 256u

// Per-material flag bits (`GpuMaterial.materialFlags`).
// Authoritative values: vulkan/material.rs `material_flag::*`. #1190.
#define MAT_FLAG_VERTEX_COLOR_EMISSIVE 1u
#define MAT_FLAG_EFFECT_SOFT 2u
#define MAT_FLAG_EFFECT_PALETTE_COLOR 4u
#define MAT_FLAG_EFFECT_PALETTE_ALPHA 8u
#define MAT_FLAG_EFFECT_LIT 16u
#define MAT_FLAG_PBR_BSDF 32u
#define MAT_FLAG_TRANSLUCENCY 64u
#define MAT_FLAG_MODEL_SPACE_NORMALS 128u
#define MAT_FLAG_TRANSLUCENCY_THICK_OBJECT 256u
#define MAT_FLAG_TRANSLUCENCY_MIX_ALBEDO 512u
#define MAT_FLAG_EFFECT_LI_SHIFT 16u

// Normal-alpha-as-spec marker bit (OR'd into `GpuMaterial.glossMapIndex`).
#define NORMAL_ALPHA_SPEC_BIT 2147483648u

// Water motion-kind enum (matches `byroredux::cell_loader::water::WaterKind`).
#define WATER_CALM 0u
#define WATER_RIVER 1u
#define WATER_RAPIDS 2u
#define WATER_WATERFALL 3u

// Debug-viz bit flags (set via console for renderer bisects).
#define DBG_BYPASS_POM 1u
#define DBG_BYPASS_DETAIL 2u
#define DBG_VIZ_NORMALS 4u
#define DBG_VIZ_TANGENT 8u
#define DBG_BYPASS_NORMAL_MAP 16u
#define DBG_RESERVED_20 32u
#define DBG_VIZ_RENDER_LAYER 64u
#define DBG_VIZ_GLASS_PASSTHRU 128u
#define DBG_DISABLE_SPECULAR_AA 256u
#define DBG_DISABLE_HALF_LAMBERT_FILL 512u
#define DBG_BYPASS_VERTEX_COLOR 1024u
#define DBG_DISABLE_AO 2048u
#define DBG_LEGACY_LIGHT_ATTEN 4096u
#define DBG_DISABLE_MULTISCATTER 8192u
#define DBG_DISABLE_ATROUS 16384u
#define DBG_DISABLE_RESTIR 32768u
#define DBG_DISABLE_SPATIAL 65536u
